local addonName, WeatherAddon = ...

local L = {};
WeatherAddon.L = L;

local function defaultFunc(L, key)
 -- If this function was called, we have no localization for this key.
 -- We could complain loudly to allow localizers to see the error of their ways, 
 -- but, for now, just return the key as its own localization. This allows you to—avoid writing the default localization out explicitly.
 return key;
end
setmetatable(L, {__index=defaultFunc});

local LOCALE = GetLocale()

if LOCALE == "enUS" then
	-- The EU English game client also
	-- uses the US English locale code.
	L["TOC_Title"] = "Weather"
	L["TOC_Notes"] = "Various weather-related options and features, including indoor weather ambience and accessory reminders."
	L["TOC_Title_Collector"] = "Weather_Collector"
	L["TOC_Notes_Collector"] = "Data storage collection for historical observed weather."
	L["SLASH_WEATHER1"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER2"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER3"] = "/weather" -- localized slash command
	L["SLASH_WEATHER4"] = "/weather" -- localized slash command

	L["Weather"] = "Weather"
	L["WeatherSpecial"] = "|cff33ccff[Weather]|r"
	L["Clear"] = "Clear"
	L["Rain"] = "Rain"
	L["Snow"] = "Snow"
	L["Sandstorm"] = "Sandstorm"
	L["Firestorm"] = "Firestorm"
	L["Miscellaneous"] = BINDING_HEADER_MISC
	L["Unknown"] = UNKNOWN

	L["ChangedWeather"] = "changed to %s, intensity %s."

	L["RightClickForSettings"] = BANK_TAB_TOOLTIP_CLICK_INSTRUCTION
	L["RainingNotification"] = "It's raining! Equip an accessory!"
	L["RandomTrackedAccessories"] = "Random (Tracked Accessories)"
	L["RemindersIgnoredForSession"] = "Accessory reminders ignored for the rest of this session."
	L["RemindersRestored"] = "Reminders have been restored for this session."
	L["IgnoreSession"] = "Ignore Session"
	L["Header_AmbienceSettings"] = "Ambience"
	L["Setting_IndoorWeatherAmbience"] = "Indoor Weather Ambience"
	L["Setting_IndoorWeatherAmbienceTT"] = "Select which weather types are allowed to play ambient sounds while indoors."
	L["Header_AccessorySettings"] = "Accessories"
	L["Setting_AccessorySounds"] = "Accessory Ambience Sounds"
	L["Setting_AccessorySoundsTT"] = "Toggle for accessory-related ambience, such as umbrellas/parasols."
	L["Setting_TrackedAccessories"] = "Tracked Accessories"
	L["Setting_TrackedAccessoriesTT"] = "Select which specific accessories play sounds during specific weathers."
	L["Setting_AccessoryReminders"] = "Show Accessory Reminders"
	L["Setting_AccessoryRemindersTT"] = "Toggle the popup reminders to use/refresh an accessory item."
	L["Setting_ReminderSound"] = "Play Reminder Sound"
	L["Setting_ReminderSoundTT"] = "Toggle the audio alert when the accessory reminder popup appears."
	L["Setting_ReminderSoundSelection"] = "Reminder Sound Selection"
	L["Setting_ReminderSoundSelectionTT"] = "Select which sound plays when the accessory reminder popup is shown."
	L["Setting_ReminderSoundVolume"] = "Reminder Sound Volume"
	L["Setting_ReminderSoundVolumeTT"] = "Adjust the volume of the accessory reminder sound."
	L["Setting_TRP3_IC_Only"] = "Only In Character (TRP3)"
	L["Setting_TRP3_IC_OnlyTT"] = "Reminders will only appear when your character is marked as 'In Character' (IC).\n\nRequires Total RP 3."
	L["Setting_WeatherAmbienceSpells"] = "Weather Ambience Spells"
	L["Setting_WeatherAmbienceSpellsTT"] = "Select which spell auras trigger ambience sounds when present, similar to accessory ambience sounds."
	L["Header_MovementSounds"] = "Movement Sounds"
	L["Setting_FallingSounds"] = "Falling Sounds"
	L["Setting_FallingSoundsTT"] = "Toggle the wind sound effects while your character is falling for a prolonged period of time."
	L["Setting_SkyridingSounds"] = "Skyriding Sounds"
	L["Setting_SkyridingSoundsTT"] = "Toggle the variable wind sound effects while your character is skyriding."
	L["Header_MinimapIcon"] = "Minimap Icon"
	L["Setting_ShowMinimapButton"] = "Show Minimap Icon Button"
	L["Setting_ShowMinimapButtonTT"] = "Toggle the minimap weather icon button."
	L["Setting_LockMinimapButton"] = "Lock Minimap Icon Button"
	L["Setting_LockMinimapButtonTT"] = "Prevents the minimap weather icon button from being moved."
	L["Setting_MinimapButtonSize"] = "Minimap Icon Button Size"
	L["Setting_MinimapButtonSizeTT"] = "Adjust the size of the minimap weather icon button."
	L["Setting_MinimapButtonRadius"] = "Minimap Icon Button Distance"
	L["Setting_MinimapButtonRadiusTT"] = "Adjust the (radius) distance of the minimap weather icon button from the minimap."
	L["Header_Notifications"] = "Notifications"
	L["Setting_WeatherMessages"] = "Weather Chat Messages"
	L["Setting_WeatherMessagesTT"] = "Toggle chat messages notifying you about changes in the weather."
	L["Setting_HideMinimapDecoration"] = "Hide Minimap Decoration"
	L["Setting_HideMinimapDecorationTT"] = "Toggles the background, stars, and border textures of the minimap weather icon button."
	L["Header_ScreenEffects"] = "Screen Effects"
	L["Setting_EnableScreenEffect"] = "Show Screen Effects"
	L["Setting_EnableScreenEffectTT"] = "Toggles the screen color effects during weather effects while outdoors."
	L["Setting_ScreenEffectWeathers"] = "Screen Effect Weathers"
	L["Setting_ScreenEffectWeathersTT"] = "Select which weather types the screen color effects apply to."
	L["Setting_ScreenEffectOpacity"] = "Screen Effect Opacity"
	L["Setting_ScreenEffectOpacityTT"] = "Adjust the opacity of the screen color effects.\n\nOpacity additionally scales with weather intensity."
	L["Setting_ResetIgnoredSession"] = "Reset Ignored Reminders"
	L["Btn_Reset"] = "Reset Reminders"
	L["Setting_ResetIgnoredSessionTT"] = "Resets the ignored reminders."
	L["Setting_DisableScreenEffectsInstances"] = "Hide in Instances"
	L["Setting_DisableScreenEffectsInstancesTT"] = "Toggles the screen color effects for weather to be hidden during certain specific instances."
	L["Setting_TooltipWeatherStats"] = "Tooltip Weather Stats"
	L["Setting_TooltipWeatherStatsTT"] = "Toggle the tooltip weather stats for regional and local weather in the current weather tooltip."
	L["RegionalWeatherOption"] = "Regional Weather"
	L["LocalWeatherOption"] = "Local Weather"
	L["Setting_IndoorWeatherVolume"] = VOLUME
	L["Setting_IndoorWeatherVolumeTT"] = OPTION_TOOLTIP_AMBIENCE_VOLUME
	L["Setting_AccessoriesAmbienceVolume"] = "Accessories Ambience Volume"
	L["Setting_AccessoriesAmbienceVolumeTT"] = "Adjusts the volume of accessories ambience."
	L["Setting_SpellAmbienceVolume"] = "Spell Ambience Volume"
	L["Setting_SpellAmbienceVolumeTT"] = "Adjusts the volume of spells ambience."
	L["Setting_FallingVolume"] = "Falling Ambience Volume"
	L["Setting_FallingVolumeTT"] = "Adjusts the volume of falling ambience."
	L["Setting_SkyridingVolume"] = "Skyriding Ambience Volume"
	L["Setting_SkyridingVolumeTT"] = "Adjusts the volume of skyriding ambience."
	L["Setting_WeatherIntensityPercent"] = "Weather Intensity Percentage"
	L["Setting_WeatherIntensityPercentTT"] = "Displays the weather intensity as a percentage rather than a 0 - 1 scale."
	L["Setting_AccessoryIconReplacement"] = "Accessory Icon Replacement"
	L["Setting_AccessoryIconReplacementTT"] = "Replaces the icons of the standard accessory items to be more accurate to the specific item."
	L["Setting_DisableRemindersInstances"] = "Hide in Instances"
	L["Setting_DisableRemindersInstancesTT"] = "Toggles the accessory reminders to be hidden during certain specific instances."

	L["Weather_Settings"] = "Weather - Settings"
	L["UIScale"] = UI_SCALE
	L["LockFrame"] = LOCK_FRAME
	L["ResetPosition"] = RESET_POSITION
	L["Settings"] = "Settings"
	L["WeatherData"] = "Almanac"
	L["WeatherForecast"] = "Weather Forecast"
	L["TimeObserved"] = "Time Observed: -- --"
	L["SelectZone"] = "Select a zone to view data"
	L["TimeObserved"] = "Time Observed: %s"
	L["UnknownMap"] = "Unknown Map %s"
	L["OtherUnknown"] = "Other / Unknown"
	L["Light"] = "Light"
	L["Medium"] = "Medium"
	L["Heavy"] = "Heavy"
	L["Day"] = "Day"
	L["Night"] = "Night"
	L["CurrentWeatherIntensity"] = "Current Weather: %s (%s)"
	L["RegionalWeather"] = "Regional Weather: %s"
	L["LocalWeather"] = "Local Weather: %s"
	L["DragToMove"] = "<Drag to Move>"

	L["Sound_BNET_VoiceChat_ChannelInvite"] = "Battlenet Voice Chat Channel Invite"
	L["Sound_AlarmClockWarning2"] = "Alarm Clock Warning 2"
	L["Sound_UI_BnetToast"] = "Battlenet Toast"
	L["FX_Ship_Bell_Chime_01"] = "FX_Ship_Bell_Chime_01"
	L["FX_Ship_Bell_Chime_02"] = "FX_Ship_Bell_Chime_02"
	L["FX_Ship_Bell_Chime_03"] = "FX_Ship_Bell_Chime_03"
	L["RaidWarning"] = "RaidWarning"
	L["FX_DarkMoonFaire_Bell"] = "FX_DarkMoonFaire_Bell"
	L["BellTollHorde"] = "BellTollHorde"
	L["BellTollTribal"] = "BellTollTribal"
	L["KharazahnBellToll"] = "KharazahnBellToll"
	L["BellTollNightElf"] = "BellTollNightElf"
	L["BellTollAlliance"] = "BellTollAlliance"

	L["Widget_ACT_Battlegrounds"] = BATTLEFIELDS
	L["Widget_ACT_Arena"] = ARENA
	L["Widget_ACT_Dungeon"] = LFG_TYPE_DUNGEON .. "/" .. PLAYER_DIFFICULTY_MYTHIC_PLUS
	L["Widget_ACT_Raids"] = RAID
	L["Widget_ACT_ScenariosDelves"] = SCENARIOS_PVEFRAME .. "/" .. DELVES_LABEL
	L["Widget_ACT_Housing"] = BINDING_HEADER_HOUSING_SYSTEM
	

return end

if LOCALE == "esMX" then
	-- Spanish (Mexico) translations go here
	L["TOC_Title"] = "Clima"
	L["TOC_Notes"] = "Varias opciones y funciones relacionadas con el clima, incluyendo ambiente climático en interiores y recordatorios de accesorios."
	L["TOC_Title_Collector"] = "Clima_Collector"
	L["TOC_Notes_Collector"] = "Colección de almacenamiento de datos para clima observado históricamente."
	L["SLASH_WEATHER1"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER2"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER3"] = "/clima" -- localized slash command
	L["SLASH_WEATHER4"] = "/clima" -- localized slash command

	L["Weather"] = "Clima"
	L["WeatherSpecial"] = "|cff33ccff[Clima]|r"
	L["Clear"] = "Despejado"
	L["Rain"] = "Lluvia"
	L["Snow"] = "Nieve"
	L["Sandstorm"] = "Tormenta de arena"
	L["Firestorm"] = "Tormenta de fuego"
	L["Miscellaneous"] = BINDING_HEADER_MISC
	L["Unknown"] = UNKNOWN

	L["ChangedWeather"] = "cambió a %s, intensidad %s."

	L["RightClickForSettings"] = BANK_TAB_TOOLTIP_CLICK_INSTRUCTION
	L["RainingNotification"] = "¡Está lloviendo! ¡Equipa un accesorio!"
	L["RandomTrackedAccessories"] = "Aleatorio (Accesorios rastreados)"
	L["RemindersIgnoredForSession"] = "Los recordatorios de accesorios se ignorarán durante el resto de esta sesión."
	L["RemindersRestored"] = "Los recordatorios han sido restaurados para esta sesión."
	L["IgnoreSession"] = "Ignorar sesión"
	L["Header_AmbienceSettings"] = "Ambiente"
	L["Setting_IndoorWeatherAmbience"] = "Ambiente climático en interiores"
	L["Setting_IndoorWeatherAmbienceTT"] = "Selecciona qué tipos de clima pueden reproducir sonidos ambientales en interiores."
	L["Header_AccessorySettings"] = "Accesorios"
	L["Setting_AccessorySounds"] = "Sonidos ambientales de accesorios"
	L["Setting_AccessorySoundsTT"] = "Alterna el ambiente relacionado con accesorios, como paraguas/sombrillas."
	L["Setting_TrackedAccessories"] = "Accesorios rastreados"
	L["Setting_TrackedAccessoriesTT"] = "Selecciona qué accesorios específicos reproducen sonidos durante ciertos climas."
	L["Setting_AccessoryReminders"] = "Mostrar recordatorios de accesorios"
	L["Setting_AccessoryRemindersTT"] = "Alterna los recordatorios emergentes para usar/renovar un accesorio."
	L["Setting_ReminderSound"] = "Reproducir sonido de recordatorio"
	L["Setting_ReminderSoundTT"] = "Alterna la alerta de audio cuando aparece el recordatorio de accesorio."
	L["Setting_ReminderSoundSelection"] = "Selección de sonido de recordatorio"
	L["Setting_ReminderSoundSelectionTT"] = "Selecciona qué sonido se reproduce cuando aparece el recordatorio."
	L["Setting_ReminderSoundVolume"] = "Volumen del sonido de recordatorio"
	L["Setting_ReminderSoundVolumeTT"] = "Ajusta el volumen del sonido de recordatorio de accesorios."
	L["Setting_TRP3_IC_Only"] = "Solo en personaje (TRP3)"
	L["Setting_TRP3_IC_OnlyTT"] = "Los recordatorios solo aparecerán cuando tu personaje esté marcado como 'En personaje' (IC).\n\nRequiere Total RP 3."
	L["Setting_WeatherAmbienceSpells"] = "Hechizos de ambiente climático"
	L["Setting_WeatherAmbienceSpellsTT"] = "Selecciona qué auras de hechizo activan sonidos ambientales al estar presentes, similar al ambiente de accesorios."
	L["Header_MovementSounds"] = "Sonidos de movimiento"
	L["Setting_FallingSounds"] = "Sonidos de caída"
	L["Setting_FallingSoundsTT"] = "Activa los efectos de sonido de viento mientras tu personaje cae durante un período prolongado."
	L["Setting_SkyridingSounds"] = "Sonidos de Skyriding"
	L["Setting_SkyridingSoundsTT"] = "Activa los efectos de sonido de viento variables mientras tu personaje usa Skyriding."
	L["Header_MinimapIcon"] = "Icono del minimapa"
	L["Setting_ShowMinimapButton"] = "Mostrar botón del icono del minimapa"
	L["Setting_ShowMinimapButtonTT"] = "Activa el botón del icono del clima en el minimapa."
	L["Setting_LockMinimapButton"] = "Bloquear botón del icono del minimapa"
	L["Setting_LockMinimapButtonTT"] = "Evita que el botón del icono del clima del minimapa pueda moverse."
	L["Setting_MinimapButtonSize"] = "Tamaño del botón del icono del minimapa"
	L["Setting_MinimapButtonSizeTT"] = "Ajusta el tamaño del botón del icono del clima del minimapa."
	L["Setting_MinimapButtonRadius"] = "Distancia del botón del icono del minimapa"
	L["Setting_MinimapButtonRadiusTT"] = "Ajusta la distancia (radio) del botón del icono del clima respecto al minimapa."
	L["Header_Notifications"] = "Notificaciones"
	L["Setting_WeatherMessages"] = "Mensajes de clima en el chat"
	L["Setting_WeatherMessagesTT"] = "Activa mensajes de chat que te notifican sobre cambios en el clima."
	L["Setting_HideMinimapDecoration"] = "Ocultar decoración del minimapa"
	L["Setting_HideMinimapDecorationTT"] = "Activa/desactiva el fondo, estrellas y texturas del borde del botón del clima del minimapa."
	L["Header_ScreenEffects"] = "Efectos de pantalla"
	L["Setting_EnableScreenEffect"] = "Mostrar efectos de pantalla"
	L["Setting_EnableScreenEffectTT"] = "Activa los efectos de color en pantalla durante efectos climáticos al aire libre."
	L["Setting_ScreenEffectWeathers"] = "Climas con efectos de pantalla"
	L["Setting_ScreenEffectWeathersTT"] = "Selecciona a qué tipos de clima se aplican los efectos de color en pantalla."
	L["Setting_ScreenEffectOpacity"] = "Opacidad de efectos de pantalla"
	L["Setting_ScreenEffectOpacityTT"] = "Ajusta la opacidad de los efectos de color en pantalla.\n\nLa opacidad también escala con la intensidad del clima."
	L["Setting_ResetIgnoredSession"] = "Restablecer recordatorios ignorados"
	L["Btn_Reset"] = "Restablecer recordatorios"
	L["Setting_ResetIgnoredSessionTT"] = "Restablece los recordatorios ignorados."
	L["Setting_DisableScreenEffectsInstances"] = "Ocultar en instancias"
	L["Setting_DisableScreenEffectsInstancesTT"] = "Oculta los efectos de color de pantalla del clima durante ciertas instancias específicas."
	L["Setting_TooltipWeatherStats"] = "Estadísticas meteorológicas en tooltip"
	L["Setting_TooltipWeatherStatsTT"] = "Activa las estadísticas meteorológicas regionales y locales en el tooltip del clima actual."
	L["RegionalWeatherOption"] = "Clima regional"
	L["LocalWeatherOption"] = "Clima local"
	L["Setting_IndoorWeatherVolume"] = VOLUME
	L["Setting_IndoorWeatherVolumeTT"] = OPTION_TOOLTIP_AMBIENCE_VOLUME
	L["Setting_AccessoriesAmbienceVolume"] = "Volumen de ambiente de accesorios"
	L["Setting_AccessoriesAmbienceVolumeTT"] = "Ajusta el volumen del ambiente de accesorios."
	L["Setting_SpellAmbienceVolume"] = "Volumen de ambiente de hechizos"
	L["Setting_SpellAmbienceVolumeTT"] = "Ajusta el volumen del ambiente de hechizos."
	L["Setting_FallingVolume"] = "Volumen de ambiente al caer"
	L["Setting_FallingVolumeTT"] = "Ajusta el volumen del ambiente al caer."
	L["Setting_SkyridingVolume"] = "Volumen de ambiente de surcacielos"
	L["Setting_SkyridingVolumeTT"] = "Ajusta el volumen del ambiente de surcacielos."
	L["Setting_WeatherIntensityPercent"] = "Porcentaje de intensidad del clima"
	L["Setting_WeatherIntensityPercentTT"] = "Muestra la intensidad del clima como porcentaje en lugar de una escala de 0 a 1."
	L["Setting_AccessoryIconReplacement"] = "Reemplazo de iconos de accesorios"
	L["Setting_AccessoryIconReplacementTT"] = "Reemplaza los iconos de los accesorios estándar para que representen con mayor precisión el objeto específico."
	L["Setting_DisableRemindersInstances"] = "Ocultar en instancias"
	L["Setting_DisableRemindersInstancesTT"] = "Oculta los recordatorios de accesorios durante ciertas instancias específicas."

	L["Weather_Settings"] = "Clima - Configuración"
	L["UIScale"] = UI_SCALE
	L["LockFrame"] = LOCK_FRAME
	L["ResetPosition"] = RESET_POSITION
	L["Settings"] = "Configuración"
	L["WeatherData"] = "Almanaque"
	L["WeatherForecast"] = "Pronóstico del tiempo"
	L["TimeObserved"] = "Hora observada: -- --"
	L["SelectZone"] = "Selecciona una zona para ver los datos"
	L["TimeObserved"] = "Hora observada: %s"
	L["UnknownMap"] = "Mapa desconocido %s"
	L["OtherUnknown"] = "Otro / Desconocido"
	L["Light"] = "Ligero"
	L["Medium"] = "Moderado"
	L["Heavy"] = "Intenso"
	L["Day"] = "Día"
	L["Night"] = "Noche"
	L["CurrentWeatherIntensity"] = "Clima actual: %s (%s)"
	L["RegionalWeather"] = "Clima regional: %s"
	L["LocalWeather"] = "Clima local: %s"
	L["DragToMove"] = "<Arrastrar para mover>"

	L["Sound_BNET_VoiceChat_ChannelInvite"] = "Invitación a canal de voz de Battle.net"
	L["Sound_AlarmClockWarning2"] = "Advertencia de despertador 2"
	L["Sound_UI_BnetToast"] = "Notificación emergente de Battle.net"

	L["Widget_ACT_Battlegrounds"] = BATTLEFIELDS
	L["Widget_ACT_Arena"] = ARENA
	L["Widget_ACT_Dungeon"] = LFG_TYPE_DUNGEON .. "/" .. PLAYER_DIFFICULTY_MYTHIC_PLUS
	L["Widget_ACT_Raids"] = RAID
	L["Widget_ACT_ScenariosDelves"] = SCENARIOS_PVEFRAME .. "/" .. DELVES_LABEL
	L["Widget_ACT_Housing"] = BINDING_HEADER_HOUSING_SYSTEM

return end

if LOCALE == "esES" then
	-- Spanish translations go here
	L["TOC_Title"] = "Clima"
	L["TOC_Notes"] = "Varias opciones y funciones relacionadas con el clima, incluyendo ambiente climático en interiores y recordatorios de accesorios."
	L["TOC_Title_Collector"] = "Clima_Collector"
	L["TOC_Notes_Collector"] = "Colección de almacenamiento de datos para clima observado históricamente."
	L["SLASH_WEATHER1"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER2"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER3"] = "/clima" -- localized slash command
	L["SLASH_WEATHER4"] = "/clima" -- localized slash command

	L["Weather"] = "Clima"
	L["WeatherSpecial"] = "|cff33ccff[Clima]|r"
	L["Clear"] = "Despejado"
	L["Rain"] = "Lluvia"
	L["Snow"] = "Nieve"
	L["Sandstorm"] = "Tormenta de arena"
	L["Firestorm"] = "Tormenta de fuego"
	L["Miscellaneous"] = BINDING_HEADER_MISC
	L["Unknown"] = UNKNOWN

	L["ChangedWeather"] = "cambió a %s, intensidad %s."

	L["RightClickForSettings"] = BANK_TAB_TOOLTIP_CLICK_INSTRUCTION
	L["RainingNotification"] = "¡Está lloviendo! ¡Equipa un accesorio!"
	L["RandomTrackedAccessories"] = "Aleatorio (Accesorios rastreados)"
	L["RemindersIgnoredForSession"] = "Los recordatorios de accesorios se ignorarán durante el resto de esta sesión."
	L["RemindersRestored"] = "Los recordatorios han sido restaurados para esta sesión."
	L["IgnoreSession"] = "Ignorar sesión"
	L["Header_AmbienceSettings"] = "Ambiente"
	L["Setting_IndoorWeatherAmbience"] = "Ambiente climático en interiores"
	L["Setting_IndoorWeatherAmbienceTT"] = "Selecciona qué tipos de clima pueden reproducir sonidos ambientales en interiores."
	L["Header_AccessorySettings"] = "Accesorios"
	L["Setting_AccessorySounds"] = "Sonidos ambientales de accesorios"
	L["Setting_AccessorySoundsTT"] = "Alterna el ambiente relacionado con accesorios, como paraguas/sombrillas."
	L["Setting_TrackedAccessories"] = "Accesorios rastreados"
	L["Setting_TrackedAccessoriesTT"] = "Selecciona qué accesorios específicos reproducen sonidos durante ciertos climas."
	L["Setting_AccessoryReminders"] = "Mostrar recordatorios de accesorios"
	L["Setting_AccessoryRemindersTT"] = "Alterna los recordatorios emergentes para usar/renovar un accesorio."
	L["Setting_ReminderSound"] = "Reproducir sonido de recordatorio"
	L["Setting_ReminderSoundTT"] = "Alterna la alerta de audio cuando aparece el recordatorio de accesorio."
	L["Setting_ReminderSoundSelection"] = "Selección de sonido de recordatorio"
	L["Setting_ReminderSoundSelectionTT"] = "Selecciona qué sonido se reproduce cuando aparece el recordatorio."
	L["Setting_ReminderSoundVolume"] = "Volumen del sonido de recordatorio"
	L["Setting_ReminderSoundVolumeTT"] = "Ajusta el volumen del sonido de recordatorio de accesorios."
	L["Setting_TRP3_IC_Only"] = "Solo en personaje (TRP3)"
	L["Setting_TRP3_IC_OnlyTT"] = "Los recordatorios solo aparecerán cuando tu personaje esté marcado como 'En personaje' (IC).\n\nRequiere Total RP 3."
	L["Setting_WeatherAmbienceSpells"] = "Hechizos de ambiente climático"
	L["Setting_WeatherAmbienceSpellsTT"] = "Selecciona qué auras de hechizo activan sonidos ambientales al estar presentes, similar al ambiente de accesorios."
	L["Header_MovementSounds"] = "Sonidos de movimiento"
	L["Setting_FallingSounds"] = "Sonidos de caída"
	L["Setting_FallingSoundsTT"] = "Activa los efectos de sonido de viento mientras tu personaje cae durante un período prolongado."
	L["Setting_SkyridingSounds"] = "Sonidos de Skyriding"
	L["Setting_SkyridingSoundsTT"] = "Activa los efectos de sonido de viento variables mientras tu personaje usa Skyriding."
	L["Header_MinimapIcon"] = "Icono del minimapa"
	L["Setting_ShowMinimapButton"] = "Mostrar botón del icono del minimapa"
	L["Setting_ShowMinimapButtonTT"] = "Activa el botón del icono del clima en el minimapa."
	L["Setting_LockMinimapButton"] = "Bloquear botón del icono del minimapa"
	L["Setting_LockMinimapButtonTT"] = "Evita que el botón del icono del clima del minimapa pueda moverse."
	L["Setting_MinimapButtonSize"] = "Tamaño del botón del icono del minimapa"
	L["Setting_MinimapButtonSizeTT"] = "Ajusta el tamaño del botón del icono del clima del minimapa."
	L["Setting_MinimapButtonRadius"] = "Distancia del botón del icono del minimapa"
	L["Setting_MinimapButtonRadiusTT"] = "Ajusta la distancia (radio) del botón del icono del clima respecto al minimapa."
	L["Header_Notifications"] = "Notificaciones"
	L["Setting_WeatherMessages"] = "Mensajes de clima en el chat"
	L["Setting_WeatherMessagesTT"] = "Activa mensajes de chat que te notifican sobre cambios en el clima."
	L["Setting_HideMinimapDecoration"] = "Ocultar decoración del minimapa"
	L["Setting_HideMinimapDecorationTT"] = "Activa/desactiva el fondo, estrellas y texturas del borde del botón del clima del minimapa."
	L["Header_ScreenEffects"] = "Efectos de pantalla"
	L["Setting_EnableScreenEffect"] = "Mostrar efectos de pantalla"
	L["Setting_EnableScreenEffectTT"] = "Activa los efectos de color en pantalla durante efectos climáticos al aire libre."
	L["Setting_ScreenEffectWeathers"] = "Climas con efectos de pantalla"
	L["Setting_ScreenEffectWeathersTT"] = "Selecciona a qué tipos de clima se aplican los efectos de color en pantalla."
	L["Setting_ScreenEffectOpacity"] = "Opacidad de efectos de pantalla"
	L["Setting_ScreenEffectOpacityTT"] = "Ajusta la opacidad de los efectos de color en pantalla.\n\nLa opacidad también escala con la intensidad del clima."
	L["Setting_ResetIgnoredSession"] = "Restablecer recordatorios ignorados"
	L["Btn_Reset"] = "Restablecer recordatorios"
	L["Setting_ResetIgnoredSessionTT"] = "Restablece los recordatorios ignorados."
	L["Setting_DisableScreenEffectsInstances"] = "Ocultar en estancias"
	L["Setting_DisableScreenEffectsInstancesTT"] = "Oculta los efectos de color de pantalla del clima durante determinadas estancias específicas."
	L["Setting_TooltipWeatherStats"] = "Estadísticas meteorológicas en tooltip"
	L["Setting_TooltipWeatherStatsTT"] = "Activa las estadísticas meteorológicas regionales y locales en el tooltip del tiempo actual."
	L["RegionalWeatherOption"] = "Clima regional"
	L["LocalWeatherOption"] = "Clima local"
	L["Setting_IndoorWeatherVolume"] = VOLUME
	L["Setting_IndoorWeatherVolumeTT"] = OPTION_TOOLTIP_AMBIENCE_VOLUME
	L["Setting_AccessoriesAmbienceVolume"] = "Volumen de ambiente de accesorios"
	L["Setting_AccessoriesAmbienceVolumeTT"] = "Ajusta el volumen del ambiente de accesorios."
	L["Setting_SpellAmbienceVolume"] = "Volumen de ambiente de hechizos"
	L["Setting_SpellAmbienceVolumeTT"] = "Ajusta el volumen del ambiente de hechizos."
	L["Setting_FallingVolume"] = "Volumen de ambiente de caída"
	L["Setting_FallingVolumeTT"] = "Ajusta el volumen del ambiente de caída."
	L["Setting_SkyridingVolume"] = "Volumen de ambiente de surcacielos"
	L["Setting_SkyridingVolumeTT"] = "Ajusta el volumen del ambiente de surcacielos."
	L["Setting_WeatherIntensityPercent"] = "Porcentaje de intensidad meteorológica"
	L["Setting_WeatherIntensityPercentTT"] = "Muestra la intensidad meteorológica como porcentaje en lugar de una escala de 0 a 1."
	L["Setting_AccessoryIconReplacement"] = "Sustitución de iconos de accesorios"
	L["Setting_AccessoryIconReplacementTT"] = "Sustituye los iconos de los accesorios estándar para que representen con mayor precisión el objeto específico."
	L["Setting_DisableRemindersInstances"] = "Ocultar en estancias"
	L["Setting_DisableRemindersInstancesTT"] = "Oculta los recordatorios de accesorios durante determinadas estancias específicas."

	L["Weather_Settings"] = "Clima - Configuración"
	L["UIScale"] = UI_SCALE
	L["LockFrame"] = LOCK_FRAME
	L["ResetPosition"] = RESET_POSITION
	L["Settings"] = "Configuración"
	L["WeatherData"] = "Almanaque"
	L["WeatherForecast"] = "Pronóstico meteorológico"
	L["TimeObserved"] = "Hora observada: -- --"
	L["SelectZone"] = "Selecciona una zona para ver los datos"
	L["TimeObserved"] = "Hora observada: %s"
	L["UnknownMap"] = "Mapa desconocido %s"
	L["OtherUnknown"] = "Otro / Desconocido"
	L["Light"] = "Ligero"
	L["Medium"] = "Moderado"
	L["Heavy"] = "Intenso"
	L["Day"] = "Día"
	L["Night"] = "Noche"
	L["CurrentWeatherIntensity"] = "Clima actual: %s (%s)"
	L["RegionalWeather"] = "Clima regional: %s"
	L["LocalWeather"] = "Clima local: %s"
	L["DragToMove"] = "<Arrastrar para mover>"

	L["Sound_BNET_VoiceChat_ChannelInvite"] = "Invitación a canal de voz de Battle.net"
	L["Sound_AlarmClockWarning2"] = "Aviso de alarma 2"
	L["Sound_UI_BnetToast"] = "Notificación emergente de Battle.net"

	L["Widget_ACT_Battlegrounds"] = BATTLEFIELDS
	L["Widget_ACT_Arena"] = ARENA
	L["Widget_ACT_Dungeon"] = LFG_TYPE_DUNGEON .. "/" .. PLAYER_DIFFICULTY_MYTHIC_PLUS
	L["Widget_ACT_Raids"] = RAID
	L["Widget_ACT_ScenariosDelves"] = SCENARIOS_PVEFRAME .. "/" .. DELVES_LABEL
	L["Widget_ACT_Housing"] = BINDING_HEADER_HOUSING_SYSTEM

return end

if LOCALE == "deDE" then
	-- German translations go here
	L["TOC_Title"] = "Wetter"
	L["TOC_Notes"] = "Verschiedene wetterbezogene Optionen und Funktionen, einschließlich Wetteratmosphäre in Innenräumen und Zubehör-Erinnerungen."
	L["TOC_Title_Collector"] = "Wetter_Collector"
	L["TOC_Notes_Collector"] = "Datenspeichersammlung für historisch beobachtetes Wetter."
	L["SLASH_WEATHER1"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER2"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER3"] = "/wetter" -- localized slash command
	L["SLASH_WEATHER4"] = "/wetter" -- localized slash command

	L["Weather"] = "Wetter"
	L["WeatherSpecial"] = "|cff33ccff[Wetter]|r"
	L["Clear"] = "Klar"
	L["Rain"] = "Regen"
	L["Snow"] = "Schnee"
	L["Sandstorm"] = "Sandsturm"
	L["Firestorm"] = "Feuersturm"
	L["Miscellaneous"] = BINDING_HEADER_MISC
	L["Unknown"] = UNKNOWN

	L["ChangedWeather"] = "wechselte zu %s, Intensität %s."

	L["RightClickForSettings"] = BANK_TAB_TOOLTIP_CLICK_INSTRUCTION
	L["RainingNotification"] = "Es regnet! Lege ein Accessoire an!"
	L["RandomTrackedAccessories"] = "Zufällig (Verfolgte Accessoires)"
	L["RemindersIgnoredForSession"] = "Accessoire-Erinnerungen werden für den Rest dieser Sitzung ignoriert."
	L["RemindersRestored"] = "Die Erinnerungen wurden für diese Sitzung wiederhergestellt."
	L["IgnoreSession"] = "Sitzung ignorieren"
	L["Header_AmbienceSettings"] = "Atmosphäre"
	L["Setting_IndoorWeatherAmbience"] = "Innenraum-Wetteratmosphäre"
	L["Setting_IndoorWeatherAmbienceTT"] = "Wähle aus, welche Wettertypen in Innenräumen Umgebungsgeräusche abspielen dürfen."
	L["Header_AccessorySettings"] = "Accessoires"
	L["Setting_AccessorySounds"] = "Accessoire-Atmosphäreklänge"
	L["Setting_AccessorySoundsTT"] = "Aktiviert atmosphärische Geräusche für Accessoires wie Regenschirme/Sonnenschirme."
	L["Setting_TrackedAccessories"] = "Verfolgte Accessoires"
	L["Setting_TrackedAccessoriesTT"] = "Wähle aus, welche Accessoires bei bestimmten Wetterlagen Geräusche abspielen."
	L["Setting_AccessoryReminders"] = "Accessoire-Erinnerungen anzeigen"
	L["Setting_AccessoryRemindersTT"] = "Aktiviert Pop-up-Erinnerungen zum Verwenden/Auffrischen eines Accessoires."
	L["Setting_ReminderSound"] = "Erinnerungston abspielen"
	L["Setting_ReminderSoundTT"] = "Aktiviert den Tonalarm, wenn die Accessoire-Erinnerung erscheint."
	L["Setting_ReminderSoundSelection"] = "Auswahl des Erinnerungstons"
	L["Setting_ReminderSoundSelectionTT"] = "Wähle aus, welcher Ton abgespielt wird, wenn die Erinnerung erscheint."
	L["Setting_ReminderSoundVolume"] = "Lautstärke des Erinnerungstons"
	L["Setting_ReminderSoundVolumeTT"] = "Passt die Lautstärke des Erinnerungstons an."
	L["Setting_TRP3_IC_Only"] = "Nur In Character (TRP3)"
	L["Setting_TRP3_IC_OnlyTT"] = "Erinnerungen erscheinen nur, wenn dein Charakter als 'In Character' (IC) markiert ist.\n\nBenötigt Total RP 3."
	L["Setting_WeatherAmbienceSpells"] = "Wetter-Atmosphärezauber"
	L["Setting_WeatherAmbienceSpellsTT"] = "Wähle aus, welche Zauber-Auren atmosphärische Geräusche auslösen, ähnlich wie Accessoire-Atmosphäre."
	L["Header_MovementSounds"] = "Bewegungsgeräusche"
	L["Setting_FallingSounds"] = "Fallgeräusche"
	L["Setting_FallingSoundsTT"] = "Aktiviert Windgeräusche, während dein Charakter über längere Zeit fällt."
	L["Setting_SkyridingSounds"] = "Himmelsreiten-Geräusche"
	L["Setting_SkyridingSoundsTT"] = "Aktiviert variable Windgeräusche, während dein Charakter Himmelsreiten nutzt."
	L["Header_MinimapIcon"] = "Minikartensymbol"
	L["Setting_ShowMinimapButton"] = "Minikarten-Symbolschaltfläche anzeigen"
	L["Setting_ShowMinimapButtonTT"] = "Aktiviert die Wetter-Symbolschaltfläche auf der Minikarte."
	L["Setting_LockMinimapButton"] = "Minikarten-Symbolschaltfläche sperren"
	L["Setting_LockMinimapButtonTT"] = "Verhindert das Verschieben der Wetter-Symbolschaltfläche auf der Minikarte."
	L["Setting_MinimapButtonSize"] = "Größe der Minikarten-Symbolschaltfläche"
	L["Setting_MinimapButtonSizeTT"] = "Passt die Größe der Wetter-Symbolschaltfläche auf der Minikarte an."
	L["Setting_MinimapButtonRadius"] = "Abstand der Minikarten-Symbolschaltfläche"
	L["Setting_MinimapButtonRadiusTT"] = "Passt den Abstand (Radius) der Wetter-Symbolschaltfläche zur Minikarte an."
	L["Header_Notifications"] = "Benachrichtigungen"
	L["Setting_WeatherMessages"] = "Wetter-Chatnachrichten"
	L["Setting_WeatherMessagesTT"] = "Aktiviert Chatnachrichten bei Wetteränderungen."
	L["Setting_HideMinimapDecoration"] = "Minikarten-Dekoration ausblenden"
	L["Setting_HideMinimapDecorationTT"] = "Blendet Hintergrund-, Stern- und Randtexturen der Wetter-Symbolschaltfläche aus."
	L["Header_ScreenEffects"] = "Bildschirmeffekte"
	L["Setting_EnableScreenEffect"] = "Bildschirmeffekte anzeigen"
	L["Setting_EnableScreenEffectTT"] = "Aktiviert Bildschirmfarbeffekte bei Wettereffekten im Freien."
	L["Setting_ScreenEffectWeathers"] = "Wetter mit Bildschirmeffekten"
	L["Setting_ScreenEffectWeathersTT"] = "Wähle aus, für welche Wettertypen Bildschirmeffekte gelten."
	L["Setting_ScreenEffectOpacity"] = "Deckkraft der Bildschirmeffekte"
	L["Setting_ScreenEffectOpacityTT"] = "Passt die Deckkraft der Bildschirmfarbeffekte an.\n\nDie Deckkraft skaliert zusätzlich mit der Wetterintensität."
	L["Setting_ResetIgnoredSession"] = "Ignorierte Erinnerungen zurücksetzen"
	L["Btn_Reset"] = "Erinnerungen zurücksetzen"
	L["Setting_ResetIgnoredSessionTT"] = "Setzt ignorierte Erinnerungen zurück."
	L["Setting_DisableScreenEffectsInstances"] = "In Instanzen ausblenden"
	L["Setting_DisableScreenEffectsInstancesTT"] = "Blendet die Wetter-Bildschirmfarbeneffekte in bestimmten Instanzen aus."
	L["Setting_TooltipWeatherStats"] = "Wetterstatistiken im Tooltip"
	L["Setting_TooltipWeatherStatsTT"] = "Aktiviert Wetterstatistiken für regionales und lokales Wetter im aktuellen Wetter-Tooltip."
	L["RegionalWeatherOption"] = "Regionales Wetter"
	L["LocalWeatherOption"] = "Lokales Wetter"
	L["Setting_IndoorWeatherVolume"] = VOLUME
	L["Setting_IndoorWeatherVolumeTT"] = OPTION_TOOLTIP_AMBIENCE_VOLUME
	L["Setting_AccessoriesAmbienceVolume"] = "Lautstärke der Accessoire-Umgebung"
	L["Setting_AccessoriesAmbienceVolumeTT"] = "Passt die Lautstärke der Accessoire-Umgebung an."
	L["Setting_SpellAmbienceVolume"] = "Lautstärke der Zauber-Umgebung"
	L["Setting_SpellAmbienceVolumeTT"] = "Passt die Lautstärke der Zauber-Umgebung an."
	L["Setting_FallingVolume"] = "Lautstärke der Fallgeräusche"
	L["Setting_FallingVolumeTT"] = "Passt die Lautstärke der Fallgeräusche an."
	L["Setting_SkyridingVolume"] = "Lautstärke der Himmelsreiten-Umgebung"
	L["Setting_SkyridingVolumeTT"] = "Passt die Lautstärke der Himmelsreiten-Umgebung an."
	L["Setting_WeatherIntensityPercent"] = "Wetterintensität in Prozent"
	L["Setting_WeatherIntensityPercentTT"] = "Zeigt die Wetterintensität als Prozentwert statt auf einer Skala von 0 bis 1 an."
	L["Setting_AccessoryIconReplacement"] = "Accessoire-Symbole ersetzen"
	L["Setting_AccessoryIconReplacementTT"] = "Ersetzt die Symbole der Standard-Accessoires durch passendere Symbole für den jeweiligen Gegenstand."
	L["Setting_DisableRemindersInstances"] = "In Instanzen ausblenden"
	L["Setting_DisableRemindersInstancesTT"] = "Blendet Accessoire-Erinnerungen in bestimmten Instanzen aus."

	L["Weather_Settings"] = "Wetter - Einstellungen"
	L["UIScale"] = UI_SCALE
	L["LockFrame"] = LOCK_FRAME
	L["ResetPosition"] = RESET_POSITION
	L["Settings"] = "Einstellungen"
	L["WeatherData"] = "Almanach"
	L["WeatherForecast"] = "Wettervorhersage"
	L["TimeObserved"] = "Beobachtete Zeit: -- --"
	L["SelectZone"] = "Wähle ein Gebiet aus, um Daten anzuzeigen"
	L["TimeObserved"] = "Beobachtete Zeit: %s"
	L["UnknownMap"] = "Unbekannte Karte %s"
	L["OtherUnknown"] = "Andere / Unbekannt"
	L["Light"] = "Leicht"
	L["Medium"] = "Mittel"
	L["Heavy"] = "Stark"
	L["Day"] = "Tag"
	L["Night"] = "Nacht"
	L["CurrentWeatherIntensity"] = "Aktuelles Wetter: %s (%s)"
	L["RegionalWeather"] = "Regionales Wetter: %s"
	L["LocalWeather"] = "Lokales Wetter: %s"
	L["DragToMove"] = "<Zum Verschieben ziehen>"

	L["Sound_BNET_VoiceChat_ChannelInvite"] = "Battle.net-Sprachchat-Kanaleinladung"
	L["Sound_AlarmClockWarning2"] = "Weckerwarnung 2"
	L["Sound_UI_BnetToast"] = "Battle.net-Benachrichtigung"

	L["Widget_ACT_Battlegrounds"] = BATTLEFIELDS
	L["Widget_ACT_Arena"] = ARENA
	L["Widget_ACT_Dungeon"] = LFG_TYPE_DUNGEON .. "/" .. PLAYER_DIFFICULTY_MYTHIC_PLUS
	L["Widget_ACT_Raids"] = RAID
	L["Widget_ACT_ScenariosDelves"] = SCENARIOS_PVEFRAME .. "/" .. DELVES_LABEL
	L["Widget_ACT_Housing"] = BINDING_HEADER_HOUSING_SYSTEM

return end

if LOCALE == "frFR" then
	-- French translations go here
	L["TOC_Title"] = "Météo"
	L["TOC_Notes"] = "Diverses options et fonctionnalités liées à la météo, y compris l’ambiance météo intérieure et les rappels d’accessoires."
	L["TOC_Title_Collector"] = "Météo_Collector"
	L["TOC_Notes_Collector"] = "Collection de stockage de données pour les observations météorologiques historiques."
	L["SLASH_WEATHER1"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER2"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER3"] = "/météo" -- localized slash command
	L["SLASH_WEATHER4"] = "/météo" -- localized slash command

	L["Weather"] = "Météo"
	L["WeatherSpecial"] = "|cff33ccff[Météo]|r"
	L["Clear"] = "Dégagé"
	L["Rain"] = "Pluie"
	L["Snow"] = "Neige"
	L["Sandstorm"] = "Tempête de sable"
	L["Firestorm"] = "Tempête de feu"
	L["Miscellaneous"] = BINDING_HEADER_MISC
	L["Unknown"] = UNKNOWN

	L["ChangedWeather"] = "a changé en %s, intensité %s."

	L["RightClickForSettings"] = BANK_TAB_TOOLTIP_CLICK_INSTRUCTION
	L["RainingNotification"] = "Il pleut ! Équipez un accessoire !"
	L["RandomTrackedAccessories"] = "Aléatoire (Accessoires suivis)"
	L["RemindersIgnoredForSession"] = "Les rappels d’accessoires seront ignorés pour le reste de cette session."
	L["RemindersRestored"] = "Les rappels ont été restaurés pour cette session."
	L["IgnoreSession"] = "Ignorer la session"
	L["Header_AmbienceSettings"] = "Ambiance"
	L["Setting_IndoorWeatherAmbience"] = "Ambiance météo intérieure"
	L["Setting_IndoorWeatherAmbienceTT"] = "Sélectionnez quels types de météo peuvent jouer des sons d’ambiance en intérieur."
	L["Header_AccessorySettings"] = "Accessoires"
	L["Setting_AccessorySounds"] = "Sons d’ambiance des accessoires"
	L["Setting_AccessorySoundsTT"] = "Active l’ambiance liée aux accessoires, tels que les parapluies/parasols."
	L["Setting_TrackedAccessories"] = "Accessoires suivis"
	L["Setting_TrackedAccessoriesTT"] = "Sélectionnez quels accessoires spécifiques jouent des sons selon certaines météos."
	L["Setting_AccessoryReminders"] = "Afficher les rappels d’accessoires"
	L["Setting_AccessoryRemindersTT"] = "Active les rappels contextuels pour utiliser/rafraîchir un accessoire."
	L["Setting_ReminderSound"] = "Jouer le son de rappel"
	L["Setting_ReminderSoundTT"] = "Active l’alerte sonore lorsque le rappel apparaît."
	L["Setting_ReminderSoundSelection"] = "Sélection du son de rappel"
	L["Setting_ReminderSoundSelectionTT"] = "Sélectionnez quel son est joué lorsque le rappel apparaît."
	L["Setting_ReminderSoundVolume"] = "Volume du son de rappel"
	L["Setting_ReminderSoundVolumeTT"] = "Ajuste le volume du son de rappel."
	L["Setting_TRP3_IC_Only"] = "Uniquement en personnage (TRP3)"
	L["Setting_TRP3_IC_OnlyTT"] = "Les rappels apparaîtront uniquement lorsque votre personnage est marqué comme 'En personnage' (IC).\n\nNécessite Total RP 3."
	L["Setting_WeatherAmbienceSpells"] = "Sorts d’ambiance météo"
	L["Setting_WeatherAmbienceSpellsTT"] = "Sélectionnez quelles auras de sort déclenchent des sons d’ambiance lorsqu’elles sont présentes, similaire aux accessoires."
	L["Header_MovementSounds"] = "Sons de déplacement"
	L["Setting_FallingSounds"] = "Sons de chute"
	L["Setting_FallingSoundsTT"] = "Active les effets sonores de vent lorsque votre personnage tombe pendant une longue durée."
	L["Setting_SkyridingSounds"] = "Sons de vol dynamique"
	L["Setting_SkyridingSoundsTT"] = "Active les effets sonores de vent variables lorsque votre personnage utilise le vol dynamique."
	L["Header_MinimapIcon"] = "Icône de minicarte"
	L["Setting_ShowMinimapButton"] = "Afficher le bouton de minicarte"
	L["Setting_ShowMinimapButtonTT"] = "Affiche le bouton météo sur la minicarte."
	L["Setting_LockMinimapButton"] = "Verrouiller le bouton de minicarte"
	L["Setting_LockMinimapButtonTT"] = "Empêche le déplacement du bouton météo de la minicarte."
	L["Setting_MinimapButtonSize"] = "Taille du bouton de minicarte"
	L["Setting_MinimapButtonSizeTT"] = "Ajuste la taille du bouton météo de la minicarte."
	L["Setting_MinimapButtonRadius"] = "Distance du bouton de minicarte"
	L["Setting_MinimapButtonRadiusTT"] = "Ajuste la distance (rayon) du bouton météo par rapport à la minicarte."
	L["Header_Notifications"] = "Notifications"
	L["Setting_WeatherMessages"] = "Messages météo dans le chat"
	L["Setting_WeatherMessagesTT"] = "Active les messages de chat vous informant des changements météo."
	L["Setting_HideMinimapDecoration"] = "Masquer la décoration de minicarte"
	L["Setting_HideMinimapDecorationTT"] = "Affiche ou masque l’arrière-plan, les étoiles et les bordures du bouton météo."
	L["Header_ScreenEffects"] = "Effets d’écran"
	L["Setting_EnableScreenEffect"] = "Afficher les effets d’écran"
	L["Setting_EnableScreenEffectTT"] = "Active les effets de couleur d’écran lors des effets météo en extérieur."
	L["Setting_ScreenEffectWeathers"] = "Météos avec effets d’écran"
	L["Setting_ScreenEffectWeathersTT"] = "Sélectionnez les types de météo auxquels les effets de couleur d’écran s’appliquent."
	L["Setting_ScreenEffectOpacity"] = "Opacité des effets d’écran"
	L["Setting_ScreenEffectOpacityTT"] = "Ajuste l’opacité des effets de couleur d’écran.\n\nL’opacité augmente également selon l’intensité de la météo."
	L["Setting_ResetIgnoredSession"] = "Réinitialiser les rappels ignorés"
	L["Btn_Reset"] = "Réinitialiser les rappels"
	L["Setting_ResetIgnoredSessionTT"] = "Réinitialise les rappels ignorés."
	L["Setting_DisableScreenEffectsInstances"] = "Masquer en instance"
	L["Setting_DisableScreenEffectsInstancesTT"] = "Masque les effets de couleur d’écran liés à la météo dans certaines instances spécifiques."
	L["Setting_TooltipWeatherStats"] = "Statistiques météo de l’infobulle"
	L["Setting_TooltipWeatherStatsTT"] = "Active les statistiques météo régionales et locales dans l’infobulle météo actuelle."
	L["RegionalWeatherOption"] = "Météo régionale"
	L["LocalWeatherOption"] = "Météo locale"
	L["Setting_IndoorWeatherVolume"] = VOLUME
	L["Setting_IndoorWeatherVolumeTT"] = OPTION_TOOLTIP_AMBIENCE_VOLUME
	L["Setting_AccessoriesAmbienceVolume"] = "Volume d’ambiance des accessoires"
	L["Setting_AccessoriesAmbienceVolumeTT"] = "Ajuste le volume de l’ambiance des accessoires."
	L["Setting_SpellAmbienceVolume"] = "Volume d’ambiance des sorts"
	L["Setting_SpellAmbienceVolumeTT"] = "Ajuste le volume de l’ambiance des sorts."
	L["Setting_FallingVolume"] = "Volume d’ambiance de chute"
	L["Setting_FallingVolumeTT"] = "Ajuste le volume de l’ambiance de chute."
	L["Setting_SkyridingVolume"] = "Volume d’ambiance de vol dynamique"
	L["Setting_SkyridingVolumeTT"] = "Ajuste le volume de l’ambiance de vol dynamique."
	L["Setting_WeatherIntensityPercent"] = "Pourcentage d’intensité météo"
	L["Setting_WeatherIntensityPercentTT"] = "Affiche l’intensité météo sous forme de pourcentage au lieu d’une échelle de 0 à 1."
	L["Setting_AccessoryIconReplacement"] = "Remplacement des icônes d’accessoires"
	L["Setting_AccessoryIconReplacementTT"] = "Remplace les icônes des accessoires standards par des icônes plus fidèles à l’objet spécifique."
	L["Setting_DisableRemindersInstances"] = "Masquer en instance"
	L["Setting_DisableRemindersInstancesTT"] = "Masque les rappels d’accessoires dans certaines instances spécifiques."

	L["Weather_Settings"] = "Météo - Paramètres"
	L["UIScale"] = UI_SCALE
	L["LockFrame"] = LOCK_FRAME
	L["ResetPosition"] = RESET_POSITION
	L["Settings"] = "Paramètres"
	L["WeatherData"] = "Almanach"
	L["WeatherForecast"] = "Prévisions météo"
	L["TimeObserved"] = "Heure observée : -- --"
	L["SelectZone"] = "Sélectionnez une zone pour voir les données"
	L["TimeObserved"] = "Heure observée : %s"
	L["UnknownMap"] = "Carte inconnue %s"
	L["OtherUnknown"] = "Autre / Inconnu"
	L["Light"] = "Faible"
	L["Medium"] = "Moyen"
	L["Heavy"] = "Fort"
	L["Day"] = "Jour"
	L["Night"] = "Nuit"
	L["CurrentWeatherIntensity"] = "Météo actuelle : %s (%s)"
	L["RegionalWeather"] = "Météo régionale : %s"
	L["LocalWeather"] = "Météo locale : %s"
	L["DragToMove"] = "<Glisser pour déplacer>"

	L["Sound_BNET_VoiceChat_ChannelInvite"] = "Invitation au canal vocal Battle.net"
	L["Sound_AlarmClockWarning2"] = "Alerte de réveil 2"
	L["Sound_UI_BnetToast"] = "Notification Battle.net"

	L["Widget_ACT_Battlegrounds"] = BATTLEFIELDS
	L["Widget_ACT_Arena"] = ARENA
	L["Widget_ACT_Dungeon"] = LFG_TYPE_DUNGEON .. "/" .. PLAYER_DIFFICULTY_MYTHIC_PLUS
	L["Widget_ACT_Raids"] = RAID
	L["Widget_ACT_ScenariosDelves"] = SCENARIOS_PVEFRAME .. "/" .. DELVES_LABEL
	L["Widget_ACT_Housing"] = BINDING_HEADER_HOUSING_SYSTEM

return end

if LOCALE == "itIT" then
	-- Italian translations go here
	L["TOC_Title"] = "Meteo"
	L["TOC_Notes"] = "Varie opzioni e funzionalità relative al meteo, inclusa l'atmosfera meteorologica al chiuso e i promemoria accessori."
	L["TOC_Title_Collector"] = "Meteo_Collector"
	L["TOC_Notes_Collector"] = "Raccolta di archiviazione dati per il meteo osservato storicamente."
	L["SLASH_WEATHER1"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER2"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER3"] = "/meteo" -- localized slash command
	L["SLASH_WEATHER4"] = "/meteo" -- localized slash command

	L["Weather"] = "Meteo"
	L["WeatherSpecial"] = "|cff33ccff[Meteo]|r"
	L["Clear"] = "Sereno"
	L["Rain"] = "Pioggia"
	L["Snow"] = "Neve"
	L["Sandstorm"] = "Tempesta di sabbia"
	L["Firestorm"] = "Tempesta di fuoco"
	L["Miscellaneous"] = BINDING_HEADER_MISC
	L["Unknown"] = UNKNOWN

	L["ChangedWeather"] = "cambiato in %s, intensità %s."

	L["RightClickForSettings"] = BANK_TAB_TOOLTIP_CLICK_INSTRUCTION
	L["RainingNotification"] = "Sta piovendo! Equipaggia un accessorio!"
	L["RandomTrackedAccessories"] = "Casuale (Accessori tracciati)"
	L["RemindersIgnoredForSession"] = "I promemoria accessori saranno ignorati per il resto della sessione."
	L["RemindersRestored"] = "I promemoria sono stati ripristinati per questa sessione."
	L["IgnoreSession"] = "Ignora sessione"
	L["Header_AmbienceSettings"] = "Atmosfera"
	L["Setting_IndoorWeatherAmbience"] = "Atmosfera meteo interna"
	L["Setting_IndoorWeatherAmbienceTT"] = "Seleziona quali tipi di meteo possono riprodurre suoni ambientali al chiuso."
	L["Header_AccessorySettings"] = "Accessori"
	L["Setting_AccessorySounds"] = "Suoni ambientali accessori"
	L["Setting_AccessorySoundsTT"] = "Attiva l’atmosfera legata agli accessori, come ombrelli/parasol."
	L["Setting_TrackedAccessories"] = "Accessori tracciati"
	L["Setting_TrackedAccessoriesTT"] = "Seleziona quali accessori specifici riproducono suoni durante specifiche condizioni meteo."
	L["Setting_AccessoryReminders"] = "Mostra promemoria accessori"
	L["Setting_AccessoryRemindersTT"] = "Attiva i promemoria popup per usare/aggiornare un accessorio."
	L["Setting_ReminderSound"] = "Riproduci suono promemoria"
	L["Setting_ReminderSoundTT"] = "Attiva l’avviso audio quando appare il promemoria."
	L["Setting_ReminderSoundSelection"] = "Selezione suono promemoria"
	L["Setting_ReminderSoundSelectionTT"] = "Seleziona quale suono riprodurre quando appare il promemoria."
	L["Setting_ReminderSoundVolume"] = "Volume suono promemoria"
	L["Setting_ReminderSoundVolumeTT"] = "Regola il volume del suono promemoria."
	L["Setting_TRP3_IC_Only"] = "Solo In Character (TRP3)"
	L["Setting_TRP3_IC_OnlyTT"] = "I promemoria appariranno solo quando il tuo personaggio è segnato come 'In Character' (IC).\n\nRichiede Total RP 3."
	L["Setting_WeatherAmbienceSpells"] = "Incantesimi atmosfera meteo"
	L["Setting_WeatherAmbienceSpellsTT"] = "Seleziona quali aure di incantesimo attivano suoni ambientali quando presenti, simili agli accessori."
	L["Header_MovementSounds"] = "Suoni di movimento"
	L["Setting_FallingSounds"] = "Suoni di caduta"
	L["Setting_FallingSoundsTT"] = "Attiva gli effetti sonori del vento mentre il tuo personaggio cade per un periodo prolungato."
	L["Setting_SkyridingSounds"] = "Suoni di Skyriding"
	L["Setting_SkyridingSoundsTT"] = "Attiva effetti sonori del vento variabili mentre il tuo personaggio usa lo Skyriding."
	L["Header_MinimapIcon"] = "Icona minimappa"
	L["Setting_ShowMinimapButton"] = "Mostra pulsante icona minimappa"
	L["Setting_ShowMinimapButtonTT"] = "Mostra il pulsante meteo sulla minimappa."
	L["Setting_LockMinimapButton"] = "Blocca pulsante icona minimappa"
	L["Setting_LockMinimapButtonTT"] = "Impedisce lo spostamento del pulsante meteo sulla minimappa."
	L["Setting_MinimapButtonSize"] = "Dimensione pulsante icona minimappa"
	L["Setting_MinimapButtonSizeTT"] = "Regola la dimensione del pulsante meteo sulla minimappa."
	L["Setting_MinimapButtonRadius"] = "Distanza pulsante icona minimappa"
	L["Setting_MinimapButtonRadiusTT"] = "Regola la distanza (raggio) del pulsante meteo dalla minimappa."
	L["Header_Notifications"] = "Notifiche"
	L["Setting_WeatherMessages"] = "Messaggi meteo in chat"
	L["Setting_WeatherMessagesTT"] = "Attiva messaggi di chat che notificano i cambiamenti del meteo."
	L["Setting_HideMinimapDecoration"] = "Nascondi decorazione minimappa"
	L["Setting_HideMinimapDecorationTT"] = "Mostra/nasconde sfondo, stelle e bordi del pulsante meteo della minimappa."
	L["Header_ScreenEffects"] = "Effetti schermo"
	L["Setting_EnableScreenEffect"] = "Mostra effetti schermo"
	L["Setting_EnableScreenEffectTT"] = "Attiva effetti di colore sullo schermo durante gli effetti meteo all'aperto."
	L["Setting_ScreenEffectWeathers"] = "Meteo con effetti schermo"
	L["Setting_ScreenEffectWeathersTT"] = "Seleziona i tipi di meteo a cui applicare gli effetti schermo."
	L["Setting_ScreenEffectOpacity"] = "Opacità effetti schermo"
	L["Setting_ScreenEffectOpacityTT"] = "Regola l'opacità degli effetti di colore sullo schermo.\n\nL'opacità varia anche in base all'intensità del meteo."
	L["Setting_ResetIgnoredSession"] = "Ripristina promemoria ignorati"
	L["Btn_Reset"] = "Ripristina promemoria"
	L["Setting_ResetIgnoredSessionTT"] = "Ripristina i promemoria ignorati."
	L["Setting_DisableScreenEffectsInstances"] = "Nascondi nelle istanze"
	L["Setting_DisableScreenEffectsInstancesTT"] = "Nasconde gli effetti colore dello schermo per il meteo durante specifiche istanze."
	L["Setting_TooltipWeatherStats"] = "Statistiche meteo nel tooltip"
	L["Setting_TooltipWeatherStatsTT"] = "Attiva le statistiche meteo regionali e locali nel tooltip del meteo attuale."
	L["RegionalWeatherOption"] = "Meteo regionale"
	L["LocalWeatherOption"] = "Meteo locale"
	L["Setting_IndoorWeatherVolume"] = VOLUME
	L["Setting_IndoorWeatherVolumeTT"] = OPTION_TOOLTIP_AMBIENCE_VOLUME
	L["Setting_AccessoriesAmbienceVolume"] = "Volume ambiente accessori"
	L["Setting_AccessoriesAmbienceVolumeTT"] = "Regola il volume dell’ambiente degli accessori."
	L["Setting_SpellAmbienceVolume"] = "Volume ambiente incantesimi"
	L["Setting_SpellAmbienceVolumeTT"] = "Regola il volume dell’ambiente degli incantesimi."
	L["Setting_FallingVolume"] = "Volume ambiente caduta"
	L["Setting_FallingVolumeTT"] = "Regola il volume dell’ambiente di caduta."
	L["Setting_SkyridingVolume"] = "Volume ambiente volo dinamico"
	L["Setting_SkyridingVolumeTT"] = "Regola il volume dell’ambiente di volo dinamico."
	L["Setting_WeatherIntensityPercent"] = "Percentuale intensità meteo"
	L["Setting_WeatherIntensityPercentTT"] = "Mostra l’intensità meteo come percentuale invece che su una scala da 0 a 1."
	L["Setting_AccessoryIconReplacement"] = "Sostituzione icone accessori"
	L["Setting_AccessoryIconReplacementTT"] = "Sostituisce le icone degli accessori standard con icone più accurate per l'oggetto specifico."
	L["Setting_DisableRemindersInstances"] = "Nascondi nelle istanze"
	L["Setting_DisableRemindersInstancesTT"] = "Nasconde i promemoria degli accessori durante specifiche istanze."

	L["Weather_Settings"] = "Meteo - Impostazioni"
	L["UIScale"] = UI_SCALE
	L["LockFrame"] = LOCK_FRAME
	L["ResetPosition"] = RESET_POSITION
	L["Settings"] = "Impostazioni"
	L["WeatherData"] = "Almanacco"
	L["WeatherForecast"] = "Previsioni meteo"
	L["TimeObserved"] = "Ora osservata: -- --"
	L["SelectZone"] = "Seleziona una zona per visualizzare i dati"
	L["TimeObserved"] = "Ora osservata: %s"
	L["UnknownMap"] = "Mappa sconosciuta %s"
	L["OtherUnknown"] = "Altro / Sconosciuto"
	L["Light"] = "Leggera"
	L["Medium"] = "Media"
	L["Heavy"] = "Intensa"
	L["Day"] = "Giorno"
	L["Night"] = "Notte"
	L["CurrentWeatherIntensity"] = "Meteo attuale: %s (%s)"
	L["RegionalWeather"] = "Meteo regionale: %s"
	L["LocalWeather"] = "Meteo locale: %s"
	L["DragToMove"] = "<Trascina per spostare>"

	L["Sound_BNET_VoiceChat_ChannelInvite"] = "Invito al canale vocale Battle.net"
	L["Sound_AlarmClockWarning2"] = "Avviso sveglia 2"
	L["Sound_UI_BnetToast"] = "Notifica Battle.net"

	L["Widget_ACT_Battlegrounds"] = BATTLEFIELDS
	L["Widget_ACT_Arena"] = ARENA
	L["Widget_ACT_Dungeon"] = LFG_TYPE_DUNGEON .. "/" .. PLAYER_DIFFICULTY_MYTHIC_PLUS
	L["Widget_ACT_Raids"] = RAID
	L["Widget_ACT_ScenariosDelves"] = SCENARIOS_PVEFRAME .. "/" .. DELVES_LABEL
	L["Widget_ACT_Housing"] = BINDING_HEADER_HOUSING_SYSTEM

return end

if LOCALE == "ptBR" then
	-- Brazilian Portuguese translations go here
	L["TOC_Title"] = "Clima"
	L["TOC_Notes"] = "Várias opções e recursos relacionados ao clima, incluindo ambiência climática interna e lembretes de acessórios."
	L["TOC_Title_Collector"] = "Clima_Collector"
	L["TOC_Notes_Collector"] = "Coleção de armazenamento de dados para clima observado historicamente."
	L["SLASH_WEATHER1"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER2"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER3"] = "/clima" -- localized slash command
	L["SLASH_WEATHER4"] = "/clima" -- localized slash command

	L["Weather"] = "Clima"
	L["WeatherSpecial"] = "|cff33ccff[Clima]|r"
	L["Clear"] = "Céu limpo"
	L["Rain"] = "Chuva"
	L["Snow"] = "Neve"
	L["Sandstorm"] = "Tempestade de areia"
	L["Firestorm"] = "Tempestade de fogo"
	L["Miscellaneous"] = BINDING_HEADER_MISC
	L["Unknown"] = UNKNOWN

	L["ChangedWeather"] = "mudou para %s, intensidade %s."

	L["RightClickForSettings"] = BANK_TAB_TOOLTIP_CLICK_INSTRUCTION
	L["RainingNotification"] = "Está chovendo! Equipe um acessório!"
	L["RandomTrackedAccessories"] = "Aleatório (Acessórios rastreados)"
	L["RemindersIgnoredForSession"] = "Os lembretes de acessórios serão ignorados pelo restante desta sessão."
	L["RemindersRestored"] = "Os lembretes foram restaurados para esta sessão."
	L["IgnoreSession"] = "Ignorar sessão"
	L["Header_AmbienceSettings"] = "Ambiência"
	L["Setting_IndoorWeatherAmbience"] = "Ambiência climática interna"
	L["Setting_IndoorWeatherAmbienceTT"] = "Selecione quais tipos de clima podem reproduzir sons ambientes em áreas internas."
	L["Header_AccessorySettings"] = "Acessórios"
	L["Setting_AccessorySounds"] = "Sons ambientes de acessórios"
	L["Setting_AccessorySoundsTT"] = "Ativa a ambiência relacionada a acessórios, como guarda-chuvas/parasóis."
	L["Setting_TrackedAccessories"] = "Acessórios rastreados"
	L["Setting_TrackedAccessoriesTT"] = "Selecione quais acessórios específicos reproduzem sons em climas específicos."
	L["Setting_AccessoryReminders"] = "Mostrar lembretes de acessórios"
	L["Setting_AccessoryRemindersTT"] = "Ativa os lembretes popup para usar/renovar um acessório."
	L["Setting_ReminderSound"] = "Reproduzir som de lembrete"
	L["Setting_ReminderSoundTT"] = "Ativa o alerta sonoro quando o popup de lembrete aparece."
	L["Setting_ReminderSoundSelection"] = "Seleção do som de lembrete"
	L["Setting_ReminderSoundSelectionTT"] = "Selecione qual som será reproduzido quando o lembrete aparecer."
	L["Setting_ReminderSoundVolume"] = "Volume do som de lembrete"
	L["Setting_ReminderSoundVolumeTT"] = "Ajusta o volume do som de lembrete."
	L["Setting_TRP3_IC_Only"] = "Somente em personagem (TRP3)"
	L["Setting_TRP3_IC_OnlyTT"] = "Os lembretes aparecerão apenas quando seu personagem estiver marcado como 'Em Personagem' (IC).\n\nRequer Total RP 3."
	L["Setting_WeatherAmbienceSpells"] = "Feitiços de ambiência climática"
	L["Setting_WeatherAmbienceSpellsTT"] = "Selecione quais auras de feitiço ativam sons ambientes quando presentes, semelhante à ambiência de acessórios."
	L["Header_MovementSounds"] = "Sons de movimento"
	L["Setting_FallingSounds"] = "Sons de queda"
	L["Setting_FallingSoundsTT"] = "Ativa efeitos sonoros de vento enquanto seu personagem cai por um longo período."
	L["Setting_SkyridingSounds"] = "Sons de Voo Dinâmico"
	L["Setting_SkyridingSoundsTT"] = "Ativa efeitos sonoros variáveis de vento enquanto seu personagem utiliza voo dinâmico."
	L["Header_MinimapIcon"] = "Ícone do minimapa"
	L["Setting_ShowMinimapButton"] = "Mostrar botão do minimapa"
	L["Setting_ShowMinimapButtonTT"] = "Ativa o botão do ícone de clima no minimapa."
	L["Setting_LockMinimapButton"] = "Bloquear botão do minimapa"
	L["Setting_LockMinimapButtonTT"] = "Impede que o botão do ícone de clima do minimapa seja movido."
	L["Setting_MinimapButtonSize"] = "Tamanho do botão do minimapa"
	L["Setting_MinimapButtonSizeTT"] = "Ajusta o tamanho do botão do ícone de clima do minimapa."
	L["Setting_MinimapButtonRadius"] = "Distância do botão do minimapa"
	L["Setting_MinimapButtonRadiusTT"] = "Ajusta a distância (raio) do botão do ícone de clima em relação ao minimapa."
	L["Header_Notifications"] = "Notificações"
	L["Setting_WeatherMessages"] = "Mensagens de clima no chat"
	L["Setting_WeatherMessagesTT"] = "Ativa mensagens no chat notificando sobre mudanças no clima."
	L["Setting_HideMinimapDecoration"] = "Ocultar decoração do minimapa"
	L["Setting_HideMinimapDecorationTT"] = "Alterna o fundo, estrelas e bordas do botão do ícone de clima do minimapa."
	L["Header_ScreenEffects"] = "Efeitos de tela"
	L["Setting_EnableScreenEffect"] = "Mostrar efeitos de tela"
	L["Setting_EnableScreenEffectTT"] = "Ativa efeitos de cor na tela durante efeitos climáticos ao ar livre."
	L["Setting_ScreenEffectWeathers"] = "Climas com efeitos de tela"
	L["Setting_ScreenEffectWeathersTT"] = "Selecione os tipos de clima aos quais os efeitos de tela serão aplicados."
	L["Setting_ScreenEffectOpacity"] = "Opacidade dos efeitos de tela"
	L["Setting_ScreenEffectOpacityTT"] = "Ajusta a opacidade dos efeitos de cor na tela.\n\nA opacidade também aumenta com a intensidade do clima."
	L["Setting_ResetIgnoredSession"] = "Redefinir lembretes ignorados"
	L["Btn_Reset"] = "Redefinir lembretes"
	L["Setting_ResetIgnoredSessionTT"] = "Redefine os lembretes ignorados."
	L["Setting_DisableScreenEffectsInstances"] = "Ocultar em instâncias"
	L["Setting_DisableScreenEffectsInstancesTT"] = "Oculta os efeitos de cor da tela do clima durante instâncias específicas."
	L["Setting_TooltipWeatherStats"] = "Estatísticas climáticas na dica"
	L["Setting_TooltipWeatherStatsTT"] = "Ativa as estatísticas climáticas regionais e locais na dica do clima atual."
	L["RegionalWeatherOption"] = "Clima regional"
	L["LocalWeatherOption"] = "Clima local"
	L["Setting_IndoorWeatherVolume"] = VOLUME
	L["Setting_IndoorWeatherVolumeTT"] = OPTION_TOOLTIP_AMBIENCE_VOLUME
	L["Setting_AccessoriesAmbienceVolume"] = "Volume da ambiência de acessórios"
	L["Setting_AccessoriesAmbienceVolumeTT"] = "Ajusta o volume da ambiência dos acessórios."
	L["Setting_SpellAmbienceVolume"] = "Volume da ambiência de feitiços"
	L["Setting_SpellAmbienceVolumeTT"] = "Ajusta o volume da ambiência dos feitiços."
	L["Setting_FallingVolume"] = "Volume da ambiência de queda"
	L["Setting_FallingVolumeTT"] = "Ajusta o volume da ambiência de queda."
	L["Setting_SkyridingVolume"] = "Volume da ambiência de Skyriding"
	L["Setting_SkyridingVolumeTT"] = "Ajusta o volume da ambiência de Skyriding."
	L["Setting_WeatherIntensityPercent"] = "Porcentagem da intensidade do clima"
	L["Setting_WeatherIntensityPercentTT"] = "Exibe a intensidade do clima como porcentagem em vez de uma escala de 0 a 1."
	L["Setting_AccessoryIconReplacement"] = "Substituição de ícones de acessórios"
	L["Setting_AccessoryIconReplacementTT"] = "Substitui os ícones dos acessórios padrão por ícones mais precisos para cada item específico."
	L["Setting_DisableRemindersInstances"] = "Ocultar em instâncias"
	L["Setting_DisableRemindersInstancesTT"] = "Oculta os lembretes de acessórios durante instâncias específicas."

	L["Weather_Settings"] = "Clima - Configurações"
	L["UIScale"] = UI_SCALE
	L["LockFrame"] = LOCK_FRAME
	L["ResetPosition"] = RESET_POSITION
	L["Settings"] = "Configurações"
	L["WeatherData"] = "Almanaque"
	L["WeatherForecast"] = "Previsão do tempo"
	L["TimeObserved"] = "Hora observada: -- --"
	L["SelectZone"] = "Selecione uma zona para visualizar os dados"
	L["TimeObserved"] = "Hora observada: %s"
	L["UnknownMap"] = "Mapa desconhecido %s"
	L["OtherUnknown"] = "Outro / Desconhecido"
	L["Light"] = "Leve"
	L["Medium"] = "Moderado"
	L["Heavy"] = "Forte"
	L["Day"] = "Dia"
	L["Night"] = "Noite"
	L["CurrentWeatherIntensity"] = "Clima atual: %s (%s)"
	L["RegionalWeather"] = "Clima regional: %s"
	L["LocalWeather"] = "Clima local: %s"
	L["DragToMove"] = "<Arraste para mover>"

	L["Sound_BNET_VoiceChat_ChannelInvite"] = "Convite para canal de voz Battle.net"
	L["Sound_AlarmClockWarning2"] = "Aviso de despertador 2"
	L["Sound_UI_BnetToast"] = "Notificação Battle.net"

	L["Widget_ACT_Battlegrounds"] = BATTLEFIELDS
	L["Widget_ACT_Arena"] = ARENA
	L["Widget_ACT_Dungeon"] = LFG_TYPE_DUNGEON .. "/" .. PLAYER_DIFFICULTY_MYTHIC_PLUS
	L["Widget_ACT_Raids"] = RAID
	L["Widget_ACT_ScenariosDelves"] = SCENARIOS_PVEFRAME .. "/" .. DELVES_LABEL
	L["Widget_ACT_Housing"] = BINDING_HEADER_HOUSING_SYSTEM

-- Note that the EU Portuguese WoW client also
-- uses the Brazilian Portuguese locale code.
return end

if LOCALE == "ruRU" then
	-- Russian translations go here
	L["TOC_Title"] = "Погода"
	L["TOC_Notes"] = "Различные параметры и функции, связанные с погодой, включая атмосферу погоды в помещениях и напоминания об аксессуарах."
	L["TOC_Title_Collector"] = "Погода_Collector"
	L["TOC_Notes_Collector"] = "Хранилище данных для исторически наблюдаемой погоды."
	L["SLASH_WEATHER1"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER2"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER3"] = "/погода" -- localized slash command
	L["SLASH_WEATHER4"] = "/погода" -- localized slash command

	L["Weather"] = "Погода"
	L["WeatherSpecial"] = "|cff33ccff[Погода]|r"
	L["Clear"] = "Ясно"
	L["Rain"] = "Дождь"
	L["Snow"] = "Снег"
	L["Sandstorm"] = "Песчаная буря"
	L["Firestorm"] = "Огненная буря"
	L["Miscellaneous"] = BINDING_HEADER_MISC
	L["Unknown"] = UNKNOWN

	L["ChangedWeather"] = "изменилась на %s, интенсивность %s."

	L["RightClickForSettings"] = BANK_TAB_TOOLTIP_CLICK_INSTRUCTION
	L["RainingNotification"] = "Идёт дождь! Наденьте аксессуар!"
	L["RandomTrackedAccessories"] = "Случайно (Отслеживаемые аксессуары)"
	L["RemindersIgnoredForSession"] = "Напоминания об аксессуарах отключены до конца текущей сессии."
	L["RemindersRestored"] = "Напоминания восстановлены для текущей сессии."
	L["IgnoreSession"] = "Игнорировать сессию"
	L["Header_AmbienceSettings"] = "Атмосфера"
	L["Setting_IndoorWeatherAmbience"] = "Атмосфера погоды в помещениях"
	L["Setting_IndoorWeatherAmbienceTT"] = "Выберите типы погоды, которым разрешено воспроизводить окружающие звуки в помещениях."
	L["Header_AccessorySettings"] = "Аксессуары"
	L["Setting_AccessorySounds"] = "Звуки атмосферы аксессуаров"
	L["Setting_AccessorySoundsTT"] = "Включает атмосферные звуки аксессуаров, таких как зонты и парасоли."
	L["Setting_TrackedAccessories"] = "Отслеживаемые аксессуары"
	L["Setting_TrackedAccessoriesTT"] = "Выберите аксессуары, которые воспроизводят звуки при определённой погоде."
	L["Setting_AccessoryReminders"] = "Показывать напоминания об аксессуарах"
	L["Setting_AccessoryRemindersTT"] = "Включает всплывающие напоминания об использовании/обновлении аксессуара."
	L["Setting_ReminderSound"] = "Воспроизводить звук напоминания"
	L["Setting_ReminderSoundTT"] = "Включает звуковое уведомление при появлении напоминания."
	L["Setting_ReminderSoundSelection"] = "Выбор звука напоминания"
	L["Setting_ReminderSoundSelectionTT"] = "Выберите звук, который будет воспроизводиться при появлении напоминания."
	L["Setting_ReminderSoundVolume"] = "Громкость звука напоминания"
	L["Setting_ReminderSoundVolumeTT"] = "Настройте громкость звука напоминания."
	L["Setting_TRP3_IC_Only"] = "Только в образе (TRP3)"
	L["Setting_TRP3_IC_OnlyTT"] = "Напоминания будут отображаться только если ваш персонаж отмечен как 'In Character' (IC).\n\nТребуется Total RP 3."
	L["Setting_WeatherAmbienceSpells"] = "Заклинания погодной атмосферы"
	L["Setting_WeatherAmbienceSpellsTT"] = "Выберите ауры заклинаний, которые запускают атмосферные звуки, подобно звукам аксессуаров."
	L["Header_MovementSounds"] = "Звуки движения"
	L["Setting_FallingSounds"] = "Звуки падения"
	L["Setting_FallingSoundsTT"] = "Включает звуковые эффекты ветра, пока ваш персонаж долго падает."
	L["Setting_SkyridingSounds"] = "Звуки небесной езды"
	L["Setting_SkyridingSoundsTT"] = "Включает изменяющиеся звуки ветра во время небесной езды."
	L["Header_MinimapIcon"] = "Значок миникарты"
	L["Setting_ShowMinimapButton"] = "Показывать кнопку на миникарте"
	L["Setting_ShowMinimapButtonTT"] = "Включает кнопку погодного значка на миникарте."
	L["Setting_LockMinimapButton"] = "Закрепить кнопку миникарты"
	L["Setting_LockMinimapButtonTT"] = "Предотвращает перемещение погодной кнопки миникарты."
	L["Setting_MinimapButtonSize"] = "Размер кнопки миникарты"
	L["Setting_MinimapButtonSizeTT"] = "Настройка размера погодной кнопки миникарты."
	L["Setting_MinimapButtonRadius"] = "Расстояние кнопки миникарты"
	L["Setting_MinimapButtonRadiusTT"] = "Настройка расстояния (радиуса) погодной кнопки от миникарты."
	L["Header_Notifications"] = "Уведомления"
	L["Setting_WeatherMessages"] = "Сообщения о погоде в чате"
	L["Setting_WeatherMessagesTT"] = "Включает сообщения в чате об изменениях погоды."
	L["Setting_HideMinimapDecoration"] = "Скрыть оформление миникарты"
	L["Setting_HideMinimapDecorationTT"] = "Переключает фон, звёзды и рамки погодной кнопки миникарты."
	L["Header_ScreenEffects"] = "Экранные эффекты"
	L["Setting_EnableScreenEffect"] = "Показывать экранные эффекты"
	L["Setting_EnableScreenEffectTT"] = "Включает цветовые эффекты экрана во время погодных эффектов на открытом воздухе."
	L["Setting_ScreenEffectWeathers"] = "Погода с экранными эффектами"
	L["Setting_ScreenEffectWeathersTT"] = "Выберите типы погоды, к которым применяются экранные эффекты."
	L["Setting_ScreenEffectOpacity"] = "Прозрачность экранных эффектов"
	L["Setting_ScreenEffectOpacityTT"] = "Настройка прозрачности экранных цветовых эффектов.\n\nПрозрачность также зависит от интенсивности погоды."
	L["Setting_ResetIgnoredSession"] = "Сбросить игнорируемые напоминания"
	L["Btn_Reset"] = "Сбросить напоминания"
	L["Setting_ResetIgnoredSessionTT"] = "Сбрасывает игнорируемые напоминания."
	L["Setting_DisableScreenEffectsInstances"] = "Скрывать в подземельях"
	L["Setting_DisableScreenEffectsInstancesTT"] = "Скрывает цветовые эффекты экрана погоды в определённых игровых подземельях и сценариях."
	L["Setting_TooltipWeatherStats"] = "Статистика погоды в подсказке"
	L["Setting_TooltipWeatherStatsTT"] = "Включает отображение региональной и локальной статистики погоды в подсказке текущей погоды."
	L["RegionalWeatherOption"] = "Региональная погода"
	L["LocalWeatherOption"] = "Местная погода"
	L["Setting_IndoorWeatherVolume"] = VOLUME
	L["Setting_IndoorWeatherVolumeTT"] = OPTION_TOOLTIP_AMBIENCE_VOLUME
	L["Setting_AccessoriesAmbienceVolume"] = "Громкость атмосферных звуков аксессуаров"
	L["Setting_AccessoriesAmbienceVolumeTT"] = "Регулирует громкость атмосферных звуков аксессуаров."
	L["Setting_SpellAmbienceVolume"] = "Громкость атмосферных звуков заклинаний"
	L["Setting_SpellAmbienceVolumeTT"] = "Регулирует громкость атмосферных звуков заклинаний."
	L["Setting_FallingVolume"] = "Громкость звуков падения"
	L["Setting_FallingVolumeTT"] = "Регулирует громкость атмосферных звуков падения."
	L["Setting_SkyridingVolume"] = "Громкость небесной езды"
	L["Setting_SkyridingVolumeTT"] = "Регулирует громкость атмосферных звуков небесной езды."
	L["Setting_WeatherIntensityPercent"] = "Процент интенсивности погоды"
	L["Setting_WeatherIntensityPercentTT"] = "Отображает интенсивность погоды в процентах вместо шкалы от 0 до 1."
	L["Setting_AccessoryIconReplacement"] = "Замена значков аксессуаров"
	L["Setting_AccessoryIconReplacementTT"] = "Заменяет значки стандартных аксессуаров на более точные изображения соответствующих предметов."
	L["Setting_DisableRemindersInstances"] = "Скрывать в подземельях"
	L["Setting_DisableRemindersInstancesTT"] = "Скрывает напоминания об аксессуарах в определённых подземельях и сценариях."

	L["Weather_Settings"] = "Погода - Настройки"
	L["UIScale"] = UI_SCALE
	L["LockFrame"] = LOCK_FRAME
	L["ResetPosition"] = RESET_POSITION
	L["Settings"] = "Настройки"
	L["WeatherData"] = "Альманах"
	L["WeatherForecast"] = "Прогноз погоды"
	L["TimeObserved"] = "Время наблюдения: -- --"
	L["SelectZone"] = "Выберите зону для просмотра данных"
	L["TimeObserved"] = "Время наблюдения: %s"
	L["UnknownMap"] = "Неизвестная карта %s"
	L["OtherUnknown"] = "Другое / Неизвестно"
	L["Light"] = "Слабая"
	L["Medium"] = "Средняя"
	L["Heavy"] = "Сильная"
	L["Day"] = "День"
	L["Night"] = "Ночь"
	L["CurrentWeatherIntensity"] = "Текущая погода: %s (%s)"
	L["RegionalWeather"] = "Региональная погода: %s"
	L["LocalWeather"] = "Местная погода: %s"
	L["DragToMove"] = "<Перетащите для перемещения>"

	L["Sound_BNET_VoiceChat_ChannelInvite"] = "Приглашение в голосовой канал Battle.net"
	L["Sound_AlarmClockWarning2"] = "Предупреждение будильника 2"
	L["Sound_UI_BnetToast"] = "Уведомление Battle.net"

	L["Widget_ACT_Battlegrounds"] = BATTLEFIELDS
	L["Widget_ACT_Arena"] = ARENA
	L["Widget_ACT_Dungeon"] = LFG_TYPE_DUNGEON .. "/" .. PLAYER_DIFFICULTY_MYTHIC_PLUS
	L["Widget_ACT_Raids"] = RAID
	L["Widget_ACT_ScenariosDelves"] = SCENARIOS_PVEFRAME .. "/" .. DELVES_LABEL
	L["Widget_ACT_Housing"] = BINDING_HEADER_HOUSING_SYSTEM

return end

if LOCALE == "koKR" then
	-- Korean translations go here
	L["TOC_Title"] = "날씨"
	L["TOC_Notes"] = "실내 날씨 분위기 및 액세서리 알림을 포함한 다양한 날씨 관련 옵션과 기능입니다."
	L["TOC_Title_Collector"] = "날씨_Collector"
	L["TOC_Notes_Collector"] = "과거 관측 날씨 데이터를 저장하는 수집기입니다."
	L["SLASH_WEATHER1"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER2"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER3"] = "/날씨" -- localized slash command
	L["SLASH_WEATHER4"] = "/날씨" -- localized slash command

	L["Weather"] = "날씨"
	L["WeatherSpecial"] = "|cff33ccff[날씨]|r"
	L["Clear"] = "맑음"
	L["Rain"] = "비"
	L["Snow"] = "눈"
	L["Sandstorm"] = "모래폭풍"
	L["Firestorm"] = "화염폭풍"
	L["Miscellaneous"] = BINDING_HEADER_MISC
	L["Unknown"] = UNKNOWN

	L["ChangedWeather"] = "%s 상태로 변경됨, 강도 %s."

	L["RightClickForSettings"] = BANK_TAB_TOOLTIP_CLICK_INSTRUCTION
	L["RainingNotification"] = "비가 오고 있습니다! 액세서리를 착용하세요!"
	L["RandomTrackedAccessories"] = "무작위 (추적된 액세서리)"
	L["RemindersIgnoredForSession"] = "이번 세션 동안 액세서리 알림이 무시됩니다."
	L["RemindersRestored"] = "이번 세션의 알림이 복원되었습니다."
	L["IgnoreSession"] = "세션 무시"
	L["Header_AmbienceSettings"] = "환경음"
	L["Setting_IndoorWeatherAmbience"] = "실내 날씨 환경음"
	L["Setting_IndoorWeatherAmbienceTT"] = "실내에서 환경음을 재생할 수 있는 날씨 유형을 선택합니다."
	L["Header_AccessorySettings"] = "액세서리"
	L["Setting_AccessorySounds"] = "액세서리 환경음"
	L["Setting_AccessorySoundsTT"] = "우산/양산 등의 액세서리 관련 환경음을 활성화합니다."
	L["Setting_TrackedAccessories"] = "추적된 액세서리"
	L["Setting_TrackedAccessoriesTT"] = "특정 날씨에 소리를 재생할 액세서리를 선택합니다."
	L["Setting_AccessoryReminders"] = "액세서리 알림 표시"
	L["Setting_AccessoryRemindersTT"] = "액세서리 사용/새로고침 팝업 알림을 활성화합니다."
	L["Setting_ReminderSound"] = "알림 소리 재생"
	L["Setting_ReminderSoundTT"] = "액세서리 알림 팝업이 나타날 때 오디오 알림을 재생합니다."
	L["Setting_ReminderSoundSelection"] = "알림 소리 선택"
	L["Setting_ReminderSoundSelectionTT"] = "액세서리 알림 팝업에 사용할 소리를 선택합니다."
	L["Setting_ReminderSoundVolume"] = "알림 소리 음량"
	L["Setting_ReminderSoundVolumeTT"] = "액세서리 알림 소리의 음량을 조절합니다."
	L["Setting_TRP3_IC_Only"] = "캐릭터 몰입 중일 때만 (TRP3)"
	L["Setting_TRP3_IC_OnlyTT"] = "캐릭터가 'In Character'(IC) 상태로 표시된 경우에만 알림이 나타납니다.\n\nTotal RP 3 필요."
	L["Setting_WeatherAmbienceSpells"] = "날씨 환경음 주문"
	L["Setting_WeatherAmbienceSpellsTT"] = "액세서리 환경음처럼 환경음을 유발하는 주문 오라를 선택합니다."
	L["Header_MovementSounds"] = "이동 소리"
	L["Setting_FallingSounds"] = "낙하 소리"
	L["Setting_FallingSoundsTT"] = "캐릭터가 장시간 낙하할 때 바람 효과음을 재생합니다."
	L["Setting_SkyridingSounds"] = "하늘비행 소리"
	L["Setting_SkyridingSoundsTT"] = "캐릭터가 하늘비행 중일 때 가변적인 바람 효과음을 재생합니다."
	L["Header_MinimapIcon"] = "미니맵 아이콘"
	L["Setting_ShowMinimapButton"] = "미니맵 아이콘 버튼 표시"
	L["Setting_ShowMinimapButtonTT"] = "미니맵 날씨 아이콘 버튼을 표시합니다."
	L["Setting_LockMinimapButton"] = "미니맵 아이콘 버튼 잠금"
	L["Setting_LockMinimapButtonTT"] = "미니맵 날씨 아이콘 버튼이 이동되지 않도록 합니다."
	L["Setting_MinimapButtonSize"] = "미니맵 아이콘 버튼 크기"
	L["Setting_MinimapButtonSizeTT"] = "미니맵 날씨 아이콘 버튼의 크기를 조정합니다."
	L["Setting_MinimapButtonRadius"] = "미니맵 아이콘 버튼 거리"
	L["Setting_MinimapButtonRadiusTT"] = "미니맵 날씨 아이콘 버튼의 미니맵 기준 거리(반경)를 조정합니다."
	L["Header_Notifications"] = "알림"
	L["Setting_WeatherMessages"] = "날씨 채팅 메시지"
	L["Setting_WeatherMessagesTT"] = "날씨 변화 알림 채팅 메시지를 표시합니다."
	L["Setting_HideMinimapDecoration"] = "미니맵 장식 숨기기"
	L["Setting_HideMinimapDecorationTT"] = "미니맵 날씨 아이콘 버튼의 배경, 별, 테두리 텍스처를 숨기거나 표시합니다."
	L["Header_ScreenEffects"] = "화면 효과"
	L["Setting_EnableScreenEffect"] = "화면 효과 표시"
	L["Setting_EnableScreenEffectTT"] = "야외 날씨 효과 중 화면 색상 효과를 표시합니다."
	L["Setting_ScreenEffectWeathers"] = "화면 효과 날씨"
	L["Setting_ScreenEffectWeathersTT"] = "화면 색상 효과를 적용할 날씨 유형을 선택합니다."
	L["Setting_ScreenEffectOpacity"] = "화면 효과 투명도"
	L["Setting_ScreenEffectOpacityTT"] = "화면 색상 효과의 투명도를 조정합니다.\n\n투명도는 날씨 강도에 따라 추가로 조정됩니다."
	L["Setting_ResetIgnoredSession"] = "무시된 알림 초기화"
	L["Btn_Reset"] = "알림 초기화"
	L["Setting_ResetIgnoredSessionTT"] = "무시된 알림을 초기화합니다."
	L["Setting_DisableScreenEffectsInstances"] = "인스턴스에서 숨기기"
	L["Setting_DisableScreenEffectsInstancesTT"] = "특정 인스턴스에서 날씨 화면 색상 효과를 숨깁니다."
	L["Setting_TooltipWeatherStats"] = "툴팁 날씨 통계"
	L["Setting_TooltipWeatherStatsTT"] = "현재 날씨 툴팁에 지역 및 현지 날씨 통계를 표시합니다."
	L["RegionalWeatherOption"] = "지역 날씨"
	L["LocalWeatherOption"] = "현지 날씨"
	L["Setting_IndoorWeatherVolume"] = VOLUME
	L["Setting_IndoorWeatherVolumeTT"] = OPTION_TOOLTIP_AMBIENCE_VOLUME
	L["Setting_AccessoriesAmbienceVolume"] = "장신구 환경음 볼륨"
	L["Setting_AccessoriesAmbienceVolumeTT"] = "장신구 환경음의 볼륨을 조절합니다."
	L["Setting_SpellAmbienceVolume"] = "주문 환경음 볼륨"
	L["Setting_SpellAmbienceVolumeTT"] = "주문 환경음의 볼륨을 조절합니다."
	L["Setting_FallingVolume"] = "낙하 환경음 볼륨"
	L["Setting_FallingVolumeTT"] = "낙하 환경음의 볼륨을 조절합니다."
	L["Setting_SkyridingVolume"] = "하늘비행 환경음 볼륨"
	L["Setting_SkyridingVolumeTT"] = "하늘비행 환경음의 볼륨을 조절합니다."
	L["Setting_WeatherIntensityPercent"] = "날씨 강도 백분율"
	L["Setting_WeatherIntensityPercentTT"] = "날씨 강도를 0~1 범위 대신 백분율로 표시합니다."
	L["Setting_AccessoryIconReplacement"] = "장신구 아이콘 교체"
	L["Setting_AccessoryIconReplacementTT"] = "기본 장신구 아이콘을 해당 아이템에 더 적합한 아이콘으로 교체합니다."
	L["Setting_DisableRemindersInstances"] = "인스턴스에서 숨기기"
	L["Setting_DisableRemindersInstancesTT"] = "특정 인스턴스에서 장신구 알림을 숨깁니다."

	L["Weather_Settings"] = "날씨 - 설정"
	L["UIScale"] = UI_SCALE
	L["LockFrame"] = LOCK_FRAME
	L["ResetPosition"] = RESET_POSITION
	L["Settings"] = "설정"
	L["WeatherData"] = "기상 연감"
	L["WeatherForecast"] = "일기 예보"
	L["TimeObserved"] = "관측 시간: -- --"
	L["SelectZone"] = "데이터를 보려면 지역을 선택하세요"
	L["TimeObserved"] = "관측 시간: %s"
	L["UnknownMap"] = "알 수 없는 지도 %s"
	L["OtherUnknown"] = "기타 / 알 수 없음"
	L["Light"] = "약함"
	L["Medium"] = "보통"
	L["Heavy"] = "강함"
	L["Day"] = "낮"
	L["Night"] = "밤"
	L["CurrentWeatherIntensity"] = "현재 날씨: %s (%s)"
	L["RegionalWeather"] = "지역 날씨: %s"
	L["LocalWeather"] = "현지 날씨: %s"
	L["DragToMove"] = "<드래그하여 이동>"

	L["Sound_BNET_VoiceChat_ChannelInvite"] = "Battle.net 음성 대화 채널 초대"
	L["Sound_AlarmClockWarning2"] = "알람 시계 경고 2"
	L["Sound_UI_BnetToast"] = "Battle.net 알림"

	L["Widget_ACT_Battlegrounds"] = BATTLEFIELDS
	L["Widget_ACT_Arena"] = ARENA
	L["Widget_ACT_Dungeon"] = LFG_TYPE_DUNGEON .. "/" .. PLAYER_DIFFICULTY_MYTHIC_PLUS
	L["Widget_ACT_Raids"] = RAID
	L["Widget_ACT_ScenariosDelves"] = SCENARIOS_PVEFRAME .. "/" .. DELVES_LABEL
	L["Widget_ACT_Housing"] = BINDING_HEADER_HOUSING_SYSTEM

return end

if LOCALE == "zhCN" then
	-- Simplified Chinese translations go here
	L["TOC_Title"] = "天气"
	L["TOC_Notes"] = "各种与天气相关的选项和功能，包括室内天气氛围与饰品提醒。"
	L["TOC_Title_Collector"] = "天气_Collector"
	L["TOC_Notes_Collector"] = "用于历史观测天气的数据存储集合。"
	L["SLASH_WEATHER1"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER2"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER3"] = "/天气" -- localized slash command
	L["SLASH_WEATHER4"] = "/天气" -- localized slash command

	L["Weather"] = "天气"
	L["WeatherSpecial"] = "|cff33ccff[天气]|r"
	L["Clear"] = "晴朗"
	L["Rain"] = "下雨"
	L["Snow"] = "下雪"
	L["Sandstorm"] = "沙尘暴"
	L["Firestorm"] = "火焰风暴"
	L["Miscellaneous"] = BINDING_HEADER_MISC
	L["Unknown"] = UNKNOWN

	L["ChangedWeather"] = "天气变为 %s，强度 %s。"

	L["RightClickForSettings"] = BANK_TAB_TOOLTIP_CLICK_INSTRUCTION
	L["RainingNotification"] = "下雨了！请装备一个饰品！"
	L["RandomTrackedAccessories"] = "随机（已追踪饰品）"
	L["RemindersIgnoredForSession"] = "本次会话剩余时间内将忽略饰品提醒。"
	L["RemindersRestored"] = "本次会话的提醒已恢复。"
	L["IgnoreSession"] = "忽略本次会话"
	L["Header_AmbienceSettings"] = "环境氛围"
	L["Setting_IndoorWeatherAmbience"] = "室内天气环境音"
	L["Setting_IndoorWeatherAmbienceTT"] = "选择哪些天气类型允许在室内播放环境音。"
	L["Header_AccessorySettings"] = "饰品"
	L["Setting_AccessorySounds"] = "饰品环境音"
	L["Setting_AccessorySoundsTT"] = "启用与饰品相关的环境音，例如雨伞/阳伞。"
	L["Setting_TrackedAccessories"] = "已追踪饰品"
	L["Setting_TrackedAccessoriesTT"] = "选择哪些饰品会在特定天气下播放声音。"
	L["Setting_AccessoryReminders"] = "显示饰品提醒"
	L["Setting_AccessoryRemindersTT"] = "启用使用/刷新饰品的弹出提醒。"
	L["Setting_ReminderSound"] = "播放提醒音效"
	L["Setting_ReminderSoundTT"] = "启用饰品提醒弹出时的声音提示。"
	L["Setting_ReminderSoundSelection"] = "提醒音效选择"
	L["Setting_ReminderSoundSelectionTT"] = "选择饰品提醒弹出时播放的声音。"
	L["Setting_ReminderSoundVolume"] = "提醒音量"
	L["Setting_ReminderSoundVolumeTT"] = "调整饰品提醒音效的音量。"
	L["Setting_TRP3_IC_Only"] = "仅角色扮演状态下（TRP3）"
	L["Setting_TRP3_IC_OnlyTT"] = "仅当你的角色被标记为“角色扮演中”(IC) 时才会显示提醒。\n\n需要 Total RP 3。"
	L["Setting_WeatherAmbienceSpells"] = "天气环境法术"
	L["Setting_WeatherAmbienceSpellsTT"] = "选择哪些法术光环存在时会触发环境音，类似于饰品环境音。"
	L["Header_MovementSounds"] = "移动音效"
	L["Setting_FallingSounds"] = "坠落音效"
	L["Setting_FallingSoundsTT"] = "角色长时间下落时播放风声效果。"
	L["Setting_SkyridingSounds"] = "驭空飞行音效"
	L["Setting_SkyridingSoundsTT"] = "角色进行驭空飞行时播放动态风声效果。"
	L["Header_MinimapIcon"] = "小地图图标"
	L["Setting_ShowMinimapButton"] = "显示小地图图标按钮"
	L["Setting_ShowMinimapButtonTT"] = "切换显示小地图天气图标按钮。"
	L["Setting_LockMinimapButton"] = "锁定小地图图标按钮"
	L["Setting_LockMinimapButtonTT"] = "防止移动小地图天气图标按钮。"
	L["Setting_MinimapButtonSize"] = "小地图图标按钮大小"
	L["Setting_MinimapButtonSizeTT"] = "调整小地图天气图标按钮的大小。"
	L["Setting_MinimapButtonRadius"] = "小地图图标按钮距离"
	L["Setting_MinimapButtonRadiusTT"] = "调整小地图天气图标按钮与小地图之间的距离（半径）。"
	L["Header_Notifications"] = "通知"
	L["Setting_WeatherMessages"] = "天气聊天消息"
	L["Setting_WeatherMessagesTT"] = "切换显示天气变化的聊天通知消息。"
	L["Setting_HideMinimapDecoration"] = "隐藏小地图装饰"
	L["Setting_HideMinimapDecorationTT"] = "切换隐藏小地图天气图标按钮的背景、星星和边框纹理。"
	L["Header_ScreenEffects"] = "屏幕效果"
	L["Setting_EnableScreenEffect"] = "显示屏幕效果"
	L["Setting_EnableScreenEffectTT"] = "在室外天气效果期间显示屏幕颜色效果。"
	L["Setting_ScreenEffectWeathers"] = "屏幕效果天气"
	L["Setting_ScreenEffectWeathersTT"] = "选择应用屏幕颜色效果的天气类型。"
	L["Setting_ScreenEffectOpacity"] = "屏幕效果透明度"
	L["Setting_ScreenEffectOpacityTT"] = "调整屏幕颜色效果的透明度。\n\n透明度还会随天气强度变化。"
	L["Setting_ResetIgnoredSession"] = "重置已忽略提醒"
	L["Btn_Reset"] = "重置提醒"
	L["Setting_ResetIgnoredSessionTT"] = "重置已忽略的提醒。"
	L["Setting_DisableScreenEffectsInstances"] = "在副本中隐藏"
	L["Setting_DisableScreenEffectsInstancesTT"] = "在某些特定副本中隐藏天气屏幕颜色效果。"
	L["Setting_TooltipWeatherStats"] = "鼠标提示天气统计"
	L["Setting_TooltipWeatherStatsTT"] = "在当前天气提示中显示区域和本地天气统计信息。"
	L["RegionalWeatherOption"] = "区域天气"
	L["LocalWeatherOption"] = "本地天气"
	L["Setting_IndoorWeatherVolume"] = VOLUME
	L["Setting_IndoorWeatherVolumeTT"] = OPTION_TOOLTIP_AMBIENCE_VOLUME
	L["Setting_AccessoriesAmbienceVolume"] = "饰品环境音量"
	L["Setting_AccessoriesAmbienceVolumeTT"] = "调整饰品环境音量。"
	L["Setting_SpellAmbienceVolume"] = "法术环境音量"
	L["Setting_SpellAmbienceVolumeTT"] = "调整法术环境音量。"
	L["Setting_FallingVolume"] = "坠落环境音量"
	L["Setting_FallingVolumeTT"] = "调整坠落环境音量。"
	L["Setting_SkyridingVolume"] = "驭空术环境音量"
	L["Setting_SkyridingVolumeTT"] = "调整驭空术环境音量。"
	L["Setting_WeatherIntensityPercent"] = "天气强度百分比"
	L["Setting_WeatherIntensityPercentTT"] = "以百分比而非 0 - 1 范围显示天气强度。"
	L["Setting_AccessoryIconReplacement"] = "饰品图标替换"
	L["Setting_AccessoryIconReplacementTT"] = "将标准饰品物品的图标替换为更符合对应物品的图标。"
	L["Setting_DisableRemindersInstances"] = "在副本中隐藏"
	L["Setting_DisableRemindersInstancesTT"] = "在某些特定副本中隐藏饰品提醒。"

	L["Weather_Settings"] = "天气 - 设置"
	L["UIScale"] = UI_SCALE
	L["LockFrame"] = LOCK_FRAME
	L["ResetPosition"] = RESET_POSITION
	L["Settings"] = "设置"
	L["WeatherData"] = "气象年鉴"
	L["WeatherForecast"] = "天气预报"
	L["TimeObserved"] = "观测时间：-- --"
	L["SelectZone"] = "选择一个区域以查看数据"
	L["TimeObserved"] = "观测时间：%s"
	L["UnknownMap"] = "未知地图 %s"
	L["OtherUnknown"] = "其他 / 未知"
	L["Light"] = "轻度"
	L["Medium"] = "中度"
	L["Heavy"] = "强烈"
	L["Day"] = "白天"
	L["Night"] = "夜晚"
	L["CurrentWeatherIntensity"] = "当前天气：%s（%s）"
	L["RegionalWeather"] = "区域天气：%s"
	L["LocalWeather"] = "本地天气：%s"
	L["DragToMove"] = "<拖动以移动>"

	L["Sound_BNET_VoiceChat_ChannelInvite"] = "Battle.net 语音聊天频道邀请"
	L["Sound_AlarmClockWarning2"] = "闹钟警告 2"
	L["Sound_UI_BnetToast"] = "Battle.net 提示通知"

	L["Widget_ACT_Battlegrounds"] = BATTLEFIELDS
	L["Widget_ACT_Arena"] = ARENA
	L["Widget_ACT_Dungeon"] = LFG_TYPE_DUNGEON .. "/" .. PLAYER_DIFFICULTY_MYTHIC_PLUS
	L["Widget_ACT_Raids"] = RAID
	L["Widget_ACT_ScenariosDelves"] = SCENARIOS_PVEFRAME .. "/" .. DELVES_LABEL
	L["Widget_ACT_Housing"] = BINDING_HEADER_HOUSING_SYSTEM

return end

if LOCALE == "zhTW" then
	-- Traditional Chinese translations go here
	L["TOC_Title"] = "天氣"
	L["TOC_Notes"] = "各種與天氣相關的選項與功能，包括室內天氣氛圍與飾品提醒。"
	L["TOC_Title_Collector"] = "天氣_Collector"
	L["TOC_Notes_Collector"] = "用於歷史觀測天氣的資料儲存集合。"
	L["SLASH_WEATHER1"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER2"] = "/weather" -- english slash command - *Do Not Localize*
	L["SLASH_WEATHER3"] = "/天氣" -- localized slash command
	L["SLASH_WEATHER4"] = "/天氣" -- localized slash command

	L["Weather"] = "天氣"
	L["WeatherSpecial"] = "|cff33ccff[天氣]|r"
	L["Clear"] = "晴朗"
	L["Rain"] = "下雨"
	L["Snow"] = "下雪"
	L["Sandstorm"] = "沙塵暴"
	L["Firestorm"] = "火焰風暴"
	L["Miscellaneous"] = BINDING_HEADER_MISC
	L["Unknown"] = UNKNOWN

	L["ChangedWeather"] = "天氣變更為 %s，強度 %s。"

	L["RightClickForSettings"] = BANK_TAB_TOOLTIP_CLICK_INSTRUCTION
	L["RainingNotification"] = "下雨了！請裝備一個飾品！"
	L["RandomTrackedAccessories"] = "隨機（已追蹤飾品）"
	L["RemindersIgnoredForSession"] = "本次階段剩餘時間內將忽略飾品提醒。"
	L["RemindersRestored"] = "本次階段的提醒已恢復。"
	L["IgnoreSession"] = "忽略本次階段"
	L["Header_AmbienceSettings"] = "環境氛圍"
	L["Setting_IndoorWeatherAmbience"] = "室內天氣環境音"
	L["Setting_IndoorWeatherAmbienceTT"] = "選擇哪些天氣類型允許在室內播放環境音。"
	L["Header_AccessorySettings"] = "飾品"
	L["Setting_AccessorySounds"] = "飾品環境音"
	L["Setting_AccessorySoundsTT"] = "啟用與飾品相關的環境音，例如雨傘/陽傘。"
	L["Setting_TrackedAccessories"] = "已追蹤飾品"
	L["Setting_TrackedAccessoriesTT"] = "選擇哪些飾品會在特定天氣下播放聲音。"
	L["Setting_AccessoryReminders"] = "顯示飾品提醒"
	L["Setting_AccessoryRemindersTT"] = "啟用使用/刷新飾品的彈出提醒。"
	L["Setting_ReminderSound"] = "播放提醒音效"
	L["Setting_ReminderSoundTT"] = "啟用飾品提醒彈出時的聲音提示。"
	L["Setting_ReminderSoundSelection"] = "提醒音效選擇"
	L["Setting_ReminderSoundSelectionTT"] = "選擇飾品提醒彈出時播放的聲音。"
	L["Setting_ReminderSoundVolume"] = "提醒音量"
	L["Setting_ReminderSoundVolumeTT"] = "調整飾品提醒音效的音量。"
	L["Setting_TRP3_IC_Only"] = "僅限角色扮演狀態（TRP3）"
	L["Setting_TRP3_IC_OnlyTT"] = "僅當你的角色被標記為「角色扮演中」(IC) 時才會顯示提醒。\n\n需要 Total RP 3。"
	L["Setting_WeatherAmbienceSpells"] = "天氣環境法術"
	L["Setting_WeatherAmbienceSpellsTT"] = "選擇哪些法術光環存在時會觸發環境音，類似於飾品環境音。"
	L["Header_MovementSounds"] = "移動音效"
	L["Setting_FallingSounds"] = "墜落音效"
	L["Setting_FallingSoundsTT"] = "角色長時間下墜時播放風聲效果。"
	L["Setting_SkyridingSounds"] = "御空飛行音效"
	L["Setting_SkyridingSoundsTT"] = "角色進行御空飛行時播放動態風聲效果。"
	L["Header_MinimapIcon"] = "小地圖圖示"
	L["Setting_ShowMinimapButton"] = "顯示小地圖圖示按鈕"
	L["Setting_ShowMinimapButtonTT"] = "切換顯示小地圖天氣圖示按鈕。"
	L["Setting_LockMinimapButton"] = "鎖定小地圖圖示按鈕"
	L["Setting_LockMinimapButtonTT"] = "防止移動小地圖天氣圖示按鈕。"
	L["Setting_MinimapButtonSize"] = "小地圖圖示按鈕大小"
	L["Setting_MinimapButtonSizeTT"] = "調整小地圖天氣圖示按鈕的大小。"
	L["Setting_MinimapButtonRadius"] = "小地圖圖示按鈕距離"
	L["Setting_MinimapButtonRadiusTT"] = "調整小地圖天氣圖示按鈕與小地圖之間的距離（半徑）。"
	L["Header_Notifications"] = "通知"
	L["Setting_WeatherMessages"] = "天氣聊天訊息"
	L["Setting_WeatherMessagesTT"] = "切換顯示天氣變化的聊天通知訊息。"
	L["Setting_HideMinimapDecoration"] = "隱藏小地圖裝飾"
	L["Setting_HideMinimapDecorationTT"] = "切換隱藏小地圖天氣圖示按鈕的背景、星星與邊框材質。"
	L["Header_ScreenEffects"] = "畫面效果"
	L["Setting_EnableScreenEffect"] = "顯示畫面效果"
	L["Setting_EnableScreenEffectTT"] = "在戶外天氣效果期間顯示畫面色彩效果。"
	L["Setting_ScreenEffectWeathers"] = "畫面效果天氣"
	L["Setting_ScreenEffectWeathersTT"] = "選擇要套用畫面色彩效果的天氣類型。"
	L["Setting_ScreenEffectOpacity"] = "畫面效果透明度"
	L["Setting_ScreenEffectOpacityTT"] = "調整畫面色彩效果的透明度。\n\n透明度也會隨天氣強度而變化。"
	L["Setting_ResetIgnoredSession"] = "重設已忽略提醒"
	L["Btn_Reset"] = "重設提醒"
	L["Setting_ResetIgnoredSessionTT"] = "重設已忽略的提醒。"
	L["Setting_DisableScreenEffectsInstances"] = "在副本中隱藏"
	L["Setting_DisableScreenEffectsInstancesTT"] = "在某些特定副本中隱藏天氣畫面色彩效果。"
	L["Setting_TooltipWeatherStats"] = "滑鼠提示天氣統計"
	L["Setting_TooltipWeatherStatsTT"] = "在目前天氣提示中顯示區域與當地天氣統計資訊。"
	L["RegionalWeatherOption"] = "區域天氣"
	L["LocalWeatherOption"] = "當地天氣"
	L["Setting_IndoorWeatherVolume"] = VOLUME
	L["Setting_IndoorWeatherVolumeTT"] = OPTION_TOOLTIP_AMBIENCE_VOLUME
	L["Setting_AccessoriesAmbienceVolume"] = "飾品環境音量"
	L["Setting_AccessoriesAmbienceVolumeTT"] = "調整飾品環境音量。"
	L["Setting_SpellAmbienceVolume"] = "法術環境音量"
	L["Setting_SpellAmbienceVolumeTT"] = "調整法術環境音量。"
	L["Setting_FallingVolume"] = "墜落環境音量"
	L["Setting_FallingVolumeTT"] = "調整墜落環境音量。"
	L["Setting_SkyridingVolume"] = "御空術環境音量"
	L["Setting_SkyridingVolumeTT"] = "調整御空術環境音量。"
	L["Setting_WeatherIntensityPercent"] = "天氣強度百分比"
	L["Setting_WeatherIntensityPercentTT"] = "以百分比而非 0 - 1 範圍顯示天氣強度。"
	L["Setting_AccessoryIconReplacement"] = "飾品圖示替換"
	L["Setting_AccessoryIconReplacementTT"] = "將標準飾品物品的圖示替換為更符合實際物品的圖示。"
	L["Setting_DisableRemindersInstances"] = "在副本中隱藏"
	L["Setting_DisableRemindersInstancesTT"] = "在某些特定副本中隱藏飾品提醒。"

	L["Weather_Settings"] = "天氣 - 設定"
	L["UIScale"] = UI_SCALE
	L["LockFrame"] = LOCK_FRAME
	L["ResetPosition"] = RESET_POSITION
	L["Settings"] = "設定"
	L["WeatherData"] = "氣象年鑑"
	L["WeatherForecast"] = "天氣預報"
	L["TimeObserved"] = "觀測時間：-- --"
	L["SelectZone"] = "選擇一個區域以檢視資料"
	L["TimeObserved"] = "觀測時間：%s"
	L["UnknownMap"] = "未知地圖 %s"
	L["OtherUnknown"] = "其他 / 未知"
	L["Light"] = "輕度"
	L["Medium"] = "中度"
	L["Heavy"] = "強烈"
	L["Day"] = "白天"
	L["Night"] = "夜晚"
	L["CurrentWeatherIntensity"] = "目前天氣：%s（%s）"
	L["RegionalWeather"] = "區域天氣：%s"
	L["LocalWeather"] = "當地天氣：%s"
	L["DragToMove"] = "<拖曳以移動>"

	L["Sound_BNET_VoiceChat_ChannelInvite"] = "Battle.net 語音聊天頻道邀請"
	L["Sound_AlarmClockWarning2"] = "鬧鐘警告 2"
	L["Sound_UI_BnetToast"] = "Battle.net 提示通知"

	L["Widget_ACT_Battlegrounds"] = BATTLEFIELDS
	L["Widget_ACT_Arena"] = ARENA
	L["Widget_ACT_Dungeon"] = LFG_TYPE_DUNGEON .. "/" .. PLAYER_DIFFICULTY_MYTHIC_PLUS
	L["Widget_ACT_Raids"] = RAID
	L["Widget_ACT_ScenariosDelves"] = SCENARIOS_PVEFRAME .. "/" .. DELVES_LABEL
	L["Widget_ACT_Housing"] = BINDING_HEADER_HOUSING_SYSTEM

return end
